create table lindholmen_shops (
	owner_id INT,
	shop_name VARCHAR(50),
	address VARCHAR(50)
);
insert into lindholmen_shops (owner_id, shop_name, address) values (5731, 'Skiles-Bartell', '43 Doe Crossing Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (3766, 'Altenwerth, Bednar and Wunsch', '270 Coleman Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (7247, 'Bashirian Group', '44922 Butterfield Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (6263, 'Fritsch LLC', '91 Banding Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (4726, 'Rice-Flatley', '438 Petterle Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (9507, 'Daugherty LLC', '86819 Myrtle Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (5472, 'Hansen-Sporer', '1765 Calypso Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (3177, 'McDermott, Morissette and Roob', '74 Northview Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1748, 'Parker Group', '7957 Burning Wood Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (1100, 'Sauer Group', '5 David Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (3938, 'Pfeffer and Sons', '0371 Londonderry Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (7257, 'Senger and Sons', '9 Nevada Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (1660, 'Sauer, Rath and Morissette', '53 Green Ridge Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (2901, 'Effertz, Hoeger and Borer', '1 Darwin Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (4573, 'Donnelly-Monahan', '45 Elmside Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (7425, 'Carroll-Kunde', '0 Ridge Oak Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2621, 'Hyatt Group', '13 Hudson Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1339, 'Bahringer, Cronin and McLaughlin', '64 Hermina Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (7394, 'Swaniawski, Harvey and Schulist', '86592 Fordem Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (5964, 'Robel and Sons', '341 Del Mar Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2185, 'Ward Group', '55 Merrick Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (2044, 'Denesik and Sons', '369 Nova Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (1318, 'Hyatt Group', '69149 Shelley Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (6159, 'Erdman, Pollich and Goodwin', '88648 Londonderry Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (7056, 'Wilderman-Kuhn', '47 Debs Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (9268, 'Paucek, Romaguera and Medhurst', '1 Welch Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8137, 'Heaney Inc', '9399 Dawn Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (4965, 'Altenwerth Inc', '289 Lindbergh Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (1143, 'Morar and Sons', '05 Dixon Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (9400, 'Torp, Cassin and Bahringer', '17 Monica Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (2696, 'Towne, Marvin and Hickle', '8 Lawn Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (6236, 'Goodwin-Davis', '517 Northport Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (7467, 'Brown Group', '19798 Monterey Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2244, 'Halvorson and Sons', '6 Hintze Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (9290, 'Bernhard LLC', '9 Darwin Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (1978, 'Daniel, Cartwright and Murazik', '92 Pearson Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (6042, 'Baumbach-Hoppe', '1 Bashford Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (3935, 'Monahan, Nienow and Rosenbaum', '99614 Meadow Vale Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (6420, 'Lindgren, Jacobi and O''Keefe', '038 Dakota Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (7613, 'Mayert-Kihn', '697 Lerdahl Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (4416, 'Schmeler Inc', '70716 Everett Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (1074, 'Walter Group', '79 Arizona Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (1871, 'Rice Inc', '310 Holmberg Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (2348, 'Stanton Inc', '91452 Dawn Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (4019, 'Dooley-Kshlerin', '87604 Forest Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (2342, 'Ward, Erdman and Hegmann', '9153 Reindahl Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (8151, 'Mosciski Inc', '92524 Lotheville Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (8443, 'Haley, Rau and Ledner', '90508 Schurz Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (3795, 'Keeling-Hilpert', '66 Brickson Park Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (2985, 'Herman and Sons', '81956 Butternut Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (5998, 'Dicki Group', '3431 Nobel Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (5868, 'Schneider Inc', '38409 Corben Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (8794, 'Hickle, Mayert and Abshire', '7 Sunfield Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (3969, 'Keebler-Raynor', '6 Maryland Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (3101, 'Greenfelder, Abbott and Block', '4316 Melody Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (5509, 'Stark-O''Keefe', '382 Hallows Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (8396, 'Leannon Group', '912 Killdeer Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (9093, 'Hilll, Effertz and Mertz', '1618 Monterey Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (1722, 'Schneider Inc', '14 Burning Wood Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (5041, 'Hauck, Kilback and Rippin', '377 Becker Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (4859, 'Padberg, Auer and Halvorson', '0642 Linden Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (9653, 'Effertz-Leannon', '558 Paget Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (1361, 'O''Hara-Collins', '1161 Springs Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (1179, 'Fay-Kuhic', '343 Badeau Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (5682, 'Weimann Inc', '9 Sheridan Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (6461, 'Tremblay, Christiansen and Jacobs', '987 Basil Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (6600, 'Quigley, Jakubowski and Wilkinson', '14388 Morrow Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8952, 'Conn, Zemlak and Bogisich', '8 Transport Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (6683, 'Osinski Inc', '051 Kenwood Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (9272, 'Osinski-Gibson', '34188 Continental Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (8879, 'Beatty-Hessel', '56 Bonner Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (2551, 'Koss and Sons', '7685 Bashford Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (6213, 'Turner-Willms', '8308 Oriole Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (3647, 'Watsica Group', '130 Columbus Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (7722, 'Klein, Okuneva and Jacobson', '291 Charing Cross Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (7742, 'Hansen, Gusikowski and Hirthe', '270 Dunning Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (2420, 'Prohaska, Hahn and Sipes', '49 Buhler Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (3697, 'Simonis LLC', '91 Hanover Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (6256, 'Funk-Ankunding', '97228 Moose Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (9847, 'Quigley LLC', '18 Marcy Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (6512, 'Cole and Sons', '35 Washington Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (3139, 'Hegmann, Conroy and Fritsch', '749 Gerald Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (3132, 'Bartoletti, Hamill and Hudson', '59 Roth Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (3261, 'Reynolds, Luettgen and Gusikowski', '88300 Arrowood Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (3663, 'Bogisich-Dooley', '2394 South Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (9763, 'Robel Inc', '8725 Mosinee Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (4956, 'Marks-Schulist', '2785 Daystar Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (9576, 'Volkman-Wintheiser', '49610 Darwin Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (1968, 'Simonis Inc', '8 Crescent Oaks Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (2869, 'Flatley-Leannon', '5015 Artisan Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (6793, 'Lubowitz-Marks', '42486 Wayridge Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (2300, 'Waters-Hand', '27 Petterle Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (6518, 'Beier Inc', '39325 Redwing Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (3216, 'Kohler, Orn and Mills', '3878 Eastwood Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2127, 'Cummings, Dickinson and Brakus', '1 Oak Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (7832, 'Kuphal, Fahey and Lubowitz', '6616 Duke Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (3972, 'Turner Inc', '323 Kingsford Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (4873, 'Mosciski-Pfannerstill', '13 Jenifer Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (6307, 'Pacocha Group', '58395 Dottie Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (8244, 'Krajcik, Bogisich and Braun', '15 Spenser Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (3622, 'Koepp Group', '26 Chive Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (8984, 'Grady-West', '0 Dakota Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (9157, 'Mante Inc', '626 Derek Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8993, 'Keebler, Mante and Bartell', '1199 Eagle Crest Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (1983, 'Johns Group', '229 Monica Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (2036, 'Thompson, Ferry and Beer', '0899 Manley Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (9661, 'DuBuque-Crooks', '34 Mayfield Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (5488, 'Grady, Barton and DuBuque', '75 Northfield Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (6339, 'Mayert-Orn', '666 Meadow Vale Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (4568, 'Kshlerin-Kunze', '53479 Sachtjen Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (9345, 'Lynch Group', '02770 Kings Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2999, 'Jast-Bartoletti', '1564 Kingsford Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (4326, 'Luettgen, Fay and Boyle', '6 Northridge Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (5308, 'Dickinson Group', '21 Sullivan Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (4459, 'Mitchell Inc', '957 Arrowood Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (9555, 'O''Connell-Ferry', '33035 Warrior Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (3836, 'Schiller and Sons', '92 Lake View Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (8545, 'Pouros Group', '0 Main Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (2897, 'Hoppe, Green and Streich', '7753 Buena Vista Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (1645, 'Bogisich Group', '35 Sunnyside Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (7057, 'Hoppe Group', '6362 Calypso Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (4945, 'Heller, Kuvalis and Walker', '89429 Merrick Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (1613, 'Hudson-Hessel', '74 Dryden Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (3583, 'Nader-McClure', '27420 Birchwood Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (4963, 'Toy Group', '9596 Packers Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8932, 'Kshlerin, Kutch and Armstrong', '20 Pierstorff Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (4720, 'Bechtelar, Abbott and Mitchell', '9 Esker Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (6939, 'Breitenberg-Brakus', '1415 6th Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (4960, 'Hessel, Ledner and Barrows', '2 Northport Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (4375, 'Klein and Sons', '0 Sunfield Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (6241, 'Schultz, Jakubowski and Auer', '025 Dixon Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (7547, 'Collier, Heller and Simonis', '502 Twin Pines Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (8327, 'Lockman Inc', '7110 Comanche Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (7770, 'Jacobi-Hills', '59339 7th Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (9207, 'Lynch, McDermott and Torp', '75 Browning Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8785, 'Mohr-Auer', '4493 Longview Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (5228, 'King Group', '8393 Scofield Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (7510, 'Lakin, Kreiger and Legros', '39 Carpenter Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (4969, 'Bernier, Gerhold and Balistreri', '699 Northview Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (8379, 'Lehner LLC', '25796 Jay Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (7254, 'Gottlieb, Bradtke and Fay', '88 Northview Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (9714, 'Lockman Group', '4217 Scott Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (5325, 'Bruen, Terry and Terry', '71 Mallard Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (2091, 'Renner Group', '71 Magdeline Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (7443, 'Williamson, Schulist and Hahn', '711 Linden Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2589, 'Langworth-Cummerata', '1 Burning Wood Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (7595, 'Dach, DuBuque and Schuppe', '62 Basil Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (2497, 'Gusikowski Group', '65 Little Fleur Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (3340, 'Mills, Schmitt and Feeney', '3 Waywood Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1093, 'Hills, Hermiston and Kerluke', '88506 Hauk Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (3993, 'Bartell, Luettgen and Lubowitz', '09840 Sheridan Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (3653, 'Lindgren, Lueilwitz and Jones', '09283 Brickson Park Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (6010, 'Schumm Inc', '25 Maywood Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (1304, 'Wuckert, Halvorson and Keeling', '46586 Cascade Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (7460, 'Kirlin-Abbott', '13 Ramsey Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (7022, 'Bode and Sons', '3376 Utah Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8923, 'Dickens-Kunze', '58 Northland Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (9458, 'Waters and Sons', '65 Golden Leaf Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (9473, 'Buckridge-Wunsch', '38 Mallory Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (3979, 'Stanton LLC', '8677 Browning Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (5227, 'Cronin Group', '92385 Pond Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (1615, 'Botsford-Hagenes', '7139 Helena Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (6003, 'Larkin, Larson and Schmitt', '1 Fisk Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8692, 'Dickens, Bartell and O''Keefe', '21623 Morningstar Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (3058, 'Tremblay Inc', '10 Scofield Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (1402, 'Rice-Osinski', '54 Clyde Gallagher Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (1785, 'Hackett-Feil', '0688 Corben Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (9252, 'Thompson, Murphy and Schroeder', '19923 Brickson Park Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (9951, 'Kessler and Sons', '9271 Village Green Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (8843, 'Weimann, Jaskolski and VonRueden', '129 Lillian Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (7703, 'Rosenbaum Inc', '1957 Redwing Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (8168, 'MacGyver-Boehm', '7 Forest Run Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (3268, 'Reichert, Cruickshank and Boehm', '9059 Porter Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (8028, 'Schiller, Fadel and Hoppe', '8 Eggendart Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2737, 'Heidenreich LLC', '802 Hayes Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (9792, 'Sipes Group', '298 Erie Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (6737, 'Ledner-Hills', '485 Dixon Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (4239, 'Conroy-Vandervort', '2598 Mayfield Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (3974, 'Ryan Group', '3 Bayside Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (7107, 'Steuber, Kub and Kozey', '9231 Orin Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (9759, 'Smith-Cummings', '62846 Hermina Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2662, 'Jakubowski-Kuphal', '8 Aberg Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (9890, 'Abbott-Bruen', '49 Judy Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (4642, 'Bayer-Russel', '95 Blackbird Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (8525, 'Monahan Group', '8029 Arrowood Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (3987, 'Gibson-Schoen', '37 Sugar Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (1754, 'Tillman-Reichert', '831 Lakewood Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (4337, 'Zieme, Kris and Rempel', '9172 Ronald Regan Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (9152, 'D''Amore Group', '2983 Trailsway Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (9478, 'Stoltenberg-Labadie', '709 Cascade Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (2416, 'Mitchell Inc', '0 Monterey Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (7785, 'Klocko Inc', '30 Kings Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (3546, 'Sanford-Towne', '3464 Lighthouse Bay Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (1758, 'Wisozk Group', '5 Reinke Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (5489, 'Sporer, Kohler and Rodriguez', '2035 Hudson Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (3375, 'Moen-Feeney', '53 Harper Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (8679, 'MacGyver-Ernser', '478 Schiller Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (1774, 'Auer Inc', '13242 Farmco Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (2309, 'Doyle Inc', '49 Lakewood Gardens Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2667, 'Wilderman Inc', '581 Rigney Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (6138, 'Oberbrunner-Konopelski', '50744 Goodland Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (3813, 'Waelchi-Swift', '411 Dahle Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (1136, 'Weimann-Wiegand', '04448 Drewry Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (1936, 'Skiles Group', '7217 Jackson Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (2118, 'Runolfsdottir and Sons', '47000 Talisman Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (5572, 'Toy-Hansen', '3018 Shelley Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (3813, 'Stroman Inc', '3870 Superior Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (9162, 'Wunsch and Sons', '5 Sullivan Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (4003, 'Corkery LLC', '11 Lyons Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (7189, 'Yost Inc', '3 Stang Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (2700, 'Konopelski and Sons', '7570 Knutson Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (7918, 'Hansen, Borer and Mayer', '5455 Delladonna Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (3913, 'Hoppe Inc', '672 2nd Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (5187, 'Swaniawski-O''Kon', '77 Kim Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (3012, 'Kshlerin, Volkman and Witting', '3 Kennedy Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (2907, 'Frami LLC', '901 Manufacturers Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (1828, 'Wiza LLC', '2 Brown Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (6402, 'Swift LLC', '47605 Helena Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (5335, 'Ankunding LLC', '435 Center Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (4007, 'Klocko, Dickens and Metz', '0425 Northwestern Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (4417, 'Blanda-DuBuque', '02 2nd Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (2906, 'Conroy Group', '50406 Nancy Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (8641, 'Orn-Schiller', '4710 Moulton Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (6947, 'Breitenberg-Johnson', '710 Namekagon Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (5605, 'Hirthe and Sons', '28390 Moulton Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (5264, 'Ebert, Hayes and Barton', '14497 Sunbrook Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (8307, 'Dickinson and Sons', '2593 Anniversary Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (3126, 'Bauch-Streich', '787 Harper Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (1452, 'O''Keefe Group', '10 Charing Cross Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (7981, 'Donnelly Group', '19 Old Shore Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2048, 'Mills, Nicolas and Halvorson', '26 Bobwhite Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (2259, 'Wilkinson and Sons', '6 Lunder Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (4681, 'Schoen, Jacobi and Friesen', '879 Clemons Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (8188, 'Greenfelder Group', '307 Harbort Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (5924, 'Spinka, Yost and Tremblay', '24937 Debs Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (1942, 'Dooley-Stanton', '3408 Fairfield Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (7907, 'Bosco, Mills and Trantow', '0 Brown Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (1481, 'Kuhn-West', '06 Miller Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1903, 'Murazik, Heller and Tillman', '3008 Manitowish Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8693, 'Langworth, Hodkiewicz and Miller', '3944 Gale Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (8091, 'Lakin, Kuhlman and Wisoky', '8812 Corben Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (9241, 'Fadel-Goodwin', '8565 Elka Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1903, 'Botsford-Ondricka', '3030 Prentice Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2983, 'Koepp LLC', '699 Norway Maple Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (6718, 'Steuber-Feest', '416 Lindbergh Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (3737, 'Schinner, Rowe and Rath', '3 Hovde Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (7248, 'Borer-Lebsack', '1552 Lillian Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (6175, 'Lueilwitz LLC', '16 Elka Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (4786, 'Considine LLC', '378 Westend Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (9990, 'Mohr, Watsica and Grimes', '96591 Autumn Leaf Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (7617, 'Parisian, Lemke and Kris', '76994 Montana Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (4590, 'Ankunding, Turner and Nitzsche', '7793 Nevada Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (1470, 'Effertz-Jacobs', '65 Dunning Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (3466, 'Spencer-Roob', '2 Pennsylvania Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (9975, 'Price Inc', '29503 Buell Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (8990, 'Braun, Pfeffer and Luettgen', '8 Dwight Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (6943, 'Grady, Senger and Prosacco', '5 Evergreen Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (2093, 'Weissnat-Tromp', '73483 2nd Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (7413, 'Sawayn-Parisian', '15 Waywood Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (9769, 'Johnson, Wehner and Daniel', '6967 Fairview Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (8701, 'Hartmann, Carter and Russel', '71277 Russell Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (8838, 'Treutel, DuBuque and Turner', '19924 Pawling Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (9264, 'McClure-Hettinger', '21116 Kipling Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (4928, 'Connelly, Nitzsche and Thiel', '43 Dryden Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (3883, 'Parker Inc', '2 Rockefeller Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (2610, 'Brekke, Beier and Schiller', '95 Springview Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (2038, 'Collins LLC', '0 Vahlen Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (9568, 'Beatty, Dach and Koss', '81273 Graceland Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (6387, 'Hilpert and Sons', '632 Pine View Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (6678, 'Jenkins and Sons', '2905 Carberry Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8747, 'Davis, Marquardt and Kautzer', '8 Cody Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (2310, 'Kemmer Inc', '4461 Sutherland Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (7943, 'Daugherty-Crooks', '5 Sunbrook Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2034, 'Stark Group', '21830 Mitchell Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (4967, 'Howell, Muller and Homenick', '721 Coleman Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (9365, 'Mayer and Sons', '72098 Derek Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (2667, 'Hilpert-Mueller', '56 Forster Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (5951, 'Dooley and Sons', '6949 Pearson Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (1528, 'Okuneva, Barrows and McLaughlin', '881 American Ash Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (4166, 'Nikolaus, Turcotte and Dicki', '542 Quincy Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (7951, 'Koepp, Klocko and Ward', '037 Sommers Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (6789, 'Beatty and Sons', '1912 Lerdahl Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (4162, 'Schamberger LLC', '1562 Village Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (3061, 'Legros-Smith', '06 Everett Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (5808, 'Schoen-Bogisich', '719 American Ash Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (6149, 'Cole, Cummings and Lebsack', '8 Mesta Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (2101, 'Murray, Stanton and Treutel', '66 Manitowish Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (2921, 'Schroeder and Sons', '559 Debs Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (3666, 'Gutkowski and Sons', '4839 Hollow Ridge Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (1372, 'Emmerich, Bergnaum and Stark', '8 Dayton Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (6057, 'Prosacco LLC', '3306 Eastwood Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (5595, 'Satterfield Group', '74 Northfield Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (6063, 'Koss, Lind and Daugherty', '6 Eastlawn Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (2688, 'Legros Inc', '68841 Sycamore Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (5035, 'Kuhn LLC', '79873 Doe Crossing Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1420, 'Becker Group', '2159 Fordem Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (7978, 'Stracke LLC', '13 Nova Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (5653, 'Beahan LLC', '6879 Meadow Vale Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8196, 'Bashirian, Harber and Reichel', '80 Farragut Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (7926, 'Fritsch-Hudson', '23 Bonner Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (3661, 'Leffler and Sons', '5 Service Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (5275, 'Barton, Daugherty and D''Amore', '3500 7th Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (5374, 'Abernathy-Keebler', '3 Kipling Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (9665, 'Murazik and Sons', '3319 Mallard Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (5989, 'Muller, Haag and Greenholt', '225 Sunnyside Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (6595, 'Marvin LLC', '9 Crescent Oaks Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (9060, 'Gottlieb Inc', '6 Hovde Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (2102, 'Hills Group', '52354 Armistice Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (1269, 'Tillman Inc', '82712 Eggendart Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (1053, 'Klocko-Grimes', '7 Banding Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8368, 'Rogahn-Lockman', '41664 Center Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (5234, 'Larkin LLC', '4 Lakewood Gardens Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (1597, 'Heidenreich LLC', '98 Ohio Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (3887, 'Kuvalis, Harvey and Runolfsdottir', '74 Blaine Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (9983, 'Wolff, Maggio and Abshire', '388 Di Loreto Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (3390, 'Dach Group', '0 Amoth Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (9143, 'Brakus and Sons', '64 Brickson Park Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (7460, 'Bauch, White and Lesch', '9149 Hudson Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (8116, 'Kuhn LLC', '08 Forest Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (2907, 'Balistreri-Stehr', '161 Prentice Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8482, 'Gottlieb-Huels', '820 Evergreen Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (4145, 'Hessel Inc', '9 Hoepker Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (1317, 'Casper and Sons', '563 Buhler Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (5934, 'Fahey LLC', '25549 Union Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (3100, 'Waters, Rau and O''Hara', '67281 Lindbergh Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (2111, 'Thompson-Halvorson', '436 Mcguire Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (1858, 'Kuhlman-Corkery', '1 Northland Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (2248, 'Olson, Boyer and Pfeffer', '98 Paget Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (7327, 'Rolfson, Hintz and Walter', '85890 Service Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2833, 'Gerhold, Windler and Lesch', '98271 Lyons Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (2076, 'Trantow, Marks and Herman', '82667 Manufacturers Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (5990, 'Kuvalis, Sipes and Hagenes', '02837 Huxley Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (5574, 'Christiansen, Balistreri and Parker', '2702 Ridge Oak Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (8973, 'Heidenreich-Hoppe', '82 Everett Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (8593, 'Williamson Inc', '88 Spaight Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (4813, 'Frami, Brekke and Mante', '36 Memorial Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (1848, 'Carroll-Koelpin', '4 Pawling Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (4756, 'Williamson, Bins and Haley', '693 Green Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (7054, 'Schiller, Oberbrunner and Schoen', '194 Hovde Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (6916, 'Feeney LLC', '3107 Gina Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (8567, 'Breitenberg-Gibson', '5199 Carey Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (3520, 'Gaylord Group', '52397 Messerschmidt Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (7058, 'Fay-Thiel', '39 Center Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2554, 'Cassin-Larkin', '00 Shopko Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (7525, 'Runte-Bergnaum', '6 Merchant Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (6002, 'Douglas Inc', '57666 Corben Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (4124, 'Murphy-Stoltenberg', '253 Fallview Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (5672, 'Cartwright, Hand and Klein', '608 Karstens Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (1875, 'Lemke, VonRueden and Bosco', '5348 Onsgard Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (6853, 'Lesch-Mosciski', '7 Schiller Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (5461, 'Bechtelar-Schultz', '17172 Barnett Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (6030, 'Green LLC', '7809 Sunbrook Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (9425, 'Muller, Daniel and Hudson', '99 Kennedy Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (4067, 'Kohler-Zieme', '5 Bellgrove Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (4574, 'Metz Group', '8 Brickson Park Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (5375, 'Mohr-Volkman', '14395 Cherokee Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (9560, 'Price-Legros', '56 Fremont Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (1523, 'Bergstrom Inc', '46921 Katie Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (5013, 'Hilpert and Sons', '63 Weeping Birch Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (6310, 'Stracke Inc', '26321 Parkside Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (5373, 'Treutel, Gorczany and McKenzie', '6699 Sunnyside Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8354, 'Ullrich-Fahey', '913 Graedel Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (1001, 'Nienow Group', '340 Hoffman Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (9036, 'Dietrich Group', '91 Oriole Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (2911, 'Wolf, Leannon and Cummings', '4 Mayer Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (1988, 'Moore-Goyette', '74 Graedel Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (5570, 'Oberbrunner, Torp and Buckridge', '357 Jay Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (4019, 'Cormier-Bruen', '70 Green Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1461, 'Tillman, Koelpin and Kutch', '5 Upham Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (9864, 'Bednar and Sons', '960 Marquette Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (2630, 'Hagenes, Rutherford and Moore', '74 Bellgrove Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (4737, 'Braun and Sons', '6069 Monica Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (8634, 'Berge-Wolf', '927 Hudson Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (9346, 'Schuster-Yost', '5279 Petterle Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (7587, 'Feil-McClure', '134 Summit Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (9202, 'Bode, Considine and Beahan', '65 Summer Ridge Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (1289, 'Cronin, Heaney and Mayer', '49 Carey Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (6177, 'Witting, Koch and Bogan', '2248 Sherman Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (5721, 'Parisian and Sons', '17599 Sauthoff Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (5185, 'Dicki-Heathcote', '6 Brickson Park Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (3480, 'Denesik Group', '7 Hudson Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (1342, 'Rice-Hagenes', '3833 Scofield Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (4966, 'Upton Group', '07 Dayton Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (2199, 'Prosacco LLC', '274 Gerald Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (6863, 'Littel, Mann and Satterfield', '219 Morrow Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (5329, 'Littel-Marks', '625 Sugar Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (7065, 'Schaden Group', '48824 Annamark Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (1573, 'Moen and Sons', '77 Quincy Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (5993, 'Lang, Bogan and Runte', '16 Algoma Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (9212, 'Maggio Group', '86 Surrey Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (8362, 'Cassin LLC', '3225 Rutledge Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (8370, 'Ebert-Rodriguez', '57 Raven Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (6793, 'Pouros-Ondricka', '89251 Gulseth Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2587, 'Glover-Schamberger', '5164 Sachtjen Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (5479, 'Konopelski-Hessel', '73846 Merry Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (5164, 'Stracke, Walker and Leannon', '8191 Union Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1217, 'Abernathy, Kihn and Lesch', '4634 Dapin Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (1559, 'Collier, Moore and Mayert', '06 La Follette Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (8162, 'Franecki Group', '3 Corben Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (2725, 'McKenzie, Reynolds and Kirlin', '85571 Novick Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (5483, 'Jacobi-Ernser', '585 School Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (3084, 'Hirthe, Okuneva and Buckridge', '02 Clemons Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (9991, 'Keebler LLC', '410 Nevada Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (1390, 'Bailey-Windler', '24066 Lakewood Gardens Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (3554, 'Kirlin-Braun', '1295 Chinook Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (1500, 'Legros-Mitchell', '36 Spohn Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (4061, 'Frami, Bruen and Kulas', '8 Russell Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (7501, 'Powlowski, Braun and Heaney', '7 Crest Line Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (5220, 'Howe Inc', '501 Duke Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (1949, 'McClure LLC', '82424 Susan Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (9364, 'Larson LLC', '051 Pearson Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8916, 'Cole, Cole and Bailey', '443 Grasskamp Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (8960, 'Herzog, Ryan and Reynolds', '18 Lake View Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (8281, 'Schmitt Inc', '000 Jenifer Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2295, 'Legros-Runolfsson', '44 Hauk Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (8849, 'Heathcote Inc', '87443 Pierstorff Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8649, 'O''Hara-Hahn', '2 Lien Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (6406, 'Hand and Sons', '38 Leroy Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (2710, 'Johnson and Sons', '068 Columbus Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (1525, 'Robel Group', '4887 Mcbride Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (2267, 'D''Amore-Bosco', '435 Glendale Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (8591, 'Bogan LLC', '10387 Petterle Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (4938, 'Gutkowski-Funk', '95916 Mayer Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (9543, 'Gorczany, Ferry and Dicki', '632 Russell Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (8305, 'Thiel-Kassulke', '47552 Summit Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (1909, 'Brown-Larkin', '0 Mcguire Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (1183, 'Considine and Sons', '19 Scoville Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1866, 'Mosciski LLC', '72625 Surrey Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (3410, 'Goyette LLC', '492 Utah Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (3578, 'King, Stracke and Pagac', '51536 Meadow Ridge Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (1071, 'Hills Group', '586 Longview Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (9914, 'Lockman, Herzog and Greenholt', '3 Macpherson Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (9151, 'Stroman-Cummerata', '9 Killdeer Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (7121, 'Pfannerstill, Ondricka and Kulas', '364 Anderson Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (8759, 'Roberts, Kautzer and Skiles', '0361 Annamark Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (8548, 'Turner-Tillman', '284 Raven Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (3129, 'Veum-Lehner', '19 Talisman Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (2718, 'Stehr and Sons', '199 Bay Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (4041, 'Rosenbaum, Krajcik and Durgan', '84521 Pearson Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (6395, 'Shanahan, Wiegand and Larkin', '72217 Thierer Avenue');
insert into lindholmen_shops (owner_id, shop_name, address) values (6106, 'O''Conner and Sons', '8578 Westridge Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (2233, 'Grimes Inc', '4 Buena Vista Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (1025, 'Wunsch, White and Boehm', '67 Morningstar Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (6037, 'Stehr-Bahringer', '7835 Ridgeview Trail');
insert into lindholmen_shops (owner_id, shop_name, address) values (7743, 'Welch Inc', '5 Judy Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (6174, 'Russel, Baumbach and Hoeger', '7 Lillian Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (5805, 'Padberg-Hoeger', '5906 Spaight Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (2335, 'Wisozk, Jacobs and Hills', '1 Graceland Center');
insert into lindholmen_shops (owner_id, shop_name, address) values (9515, 'Keebler-Hammes', '94 Golf Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8547, 'Durgan, Gleichner and Mohr', '6697 Kim Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (5235, 'Simonis-Lesch', '0 Sachtjen Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (4817, 'Gulgowski, Littel and Bernhard', '7 Sutteridge Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (4901, 'Fay-Bode', '1 Pepper Wood Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (8845, 'Sawayn and Sons', '418 Killdeer Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (7557, 'Rohan and Sons', '21 Schurz Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (7589, 'VonRueden-Volkman', '148 Hoffman Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (7075, 'Jacobi-Schultz', '2657 Birchwood Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (5228, 'Fahey, Glover and Stracke', '21 Tony Lane');
insert into lindholmen_shops (owner_id, shop_name, address) values (2129, 'VonRueden-Keebler', '36083 Burrows Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (9063, 'Rodriguez-Rohan', '266 Eastlawn Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (6186, 'Barton Inc', '31 Truax Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (5882, 'Lehner-Durgan', '3 Schiller Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (3770, 'Lind-Morar', '0 Mccormick Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (3573, 'Hammes-Little', '122 Hermina Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (2066, 'Kreiger-Von', '2599 Hagan Way');
insert into lindholmen_shops (owner_id, shop_name, address) values (8821, 'Kuhic, Rogahn and Howell', '4 Vidon Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (8607, 'Gleason, Schneider and Howell', '8780 Calypso Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (2585, 'Carroll, Hartmann and Berge', '3548 Arizona Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (2397, 'Renner-Gibson', '65418 Laurel Place');
insert into lindholmen_shops (owner_id, shop_name, address) values (6693, 'Grady-Connelly', '396 Kingsford Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (3855, 'Witting, Volkman and Stamm', '13958 Florence Hill');
insert into lindholmen_shops (owner_id, shop_name, address) values (6236, 'Steuber-Stanton', '01015 Comanche Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (9006, 'Kutch, Schultz and Streich', '06317 Continental Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (9751, 'Becker, Boehm and Fadel', '99585 Northridge Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (8596, 'Goodwin-Kulas', '46893 Kinsman Crossing');
insert into lindholmen_shops (owner_id, shop_name, address) values (1854, 'Marks-Mertz', '1 Basil Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (1341, 'Hilll and Sons', '55357 Butternut Terrace');
insert into lindholmen_shops (owner_id, shop_name, address) values (3014, 'Bailey LLC', '69 Mallard Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (8569, 'Willms Group', '3758 Kinsman Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (2627, 'Kutch, Kub and Kihn', '214 Main Court');
insert into lindholmen_shops (owner_id, shop_name, address) values (4911, 'Kshlerin, Parisian and Goldner', '96172 Rutledge Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (1958, 'Harber-Torphy', '98 Elmside Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (2410, 'Lind-Larkin', '0 Knutson Parkway');
insert into lindholmen_shops (owner_id, shop_name, address) values (8210, 'Spinka Group', '03351 Maryland Alley');
insert into lindholmen_shops (owner_id, shop_name, address) values (4479, 'Stark-Cormier', '4 Forster Drive');
insert into lindholmen_shops (owner_id, shop_name, address) values (2480, 'Bahringer-Durgan', '69244 Manley Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (3663, 'Sanford-Boyer', '809 Washington Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (3204, 'Leffler, Toy and Metz', '8 Mifflin Pass');
insert into lindholmen_shops (owner_id, shop_name, address) values (9388, 'Hilll-Schumm', '338 Hazelcrest Road');
insert into lindholmen_shops (owner_id, shop_name, address) values (3426, 'Goodwin-O''Hara', '3307 Forest Run Plaza');
insert into lindholmen_shops (owner_id, shop_name, address) values (7742, 'Mitchell LLC', '4 Colorado Point');
insert into lindholmen_shops (owner_id, shop_name, address) values (6492, 'Mohr, Oberbrunner and Lowe', '94 Bashford Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2422, 'Johnson and Sons', '35311 Merchant Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (2683, 'West-Brekke', '1 Blackbird Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (9817, 'Purdy and Sons', '01616 Gerald Junction');
insert into lindholmen_shops (owner_id, shop_name, address) values (3876, 'Leffler-Welch', '3842 Pond Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (6823, 'Wintheiser-Jaskolski', '053 Lindbergh Street');
insert into lindholmen_shops (owner_id, shop_name, address) values (9199, 'Ondricka-Luettgen', '4141 Huxley Park');
insert into lindholmen_shops (owner_id, shop_name, address) values (5567, 'Volkman Inc', '86954 Hallows Circle');
insert into lindholmen_shops (owner_id, shop_name, address) values (4750, 'Huel Group', '768 Northland Circle');
