create table persons_in_gothenburg (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	person_number INT
);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (452, 'Cécile', 'Doxycycline', 5702);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (109, 'Anaël', 'Carbidopa and Levodopa', 3218);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (253, 'Agnès', 'Instant Hand Sanitizer Convenience Pack', 9949);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (996, 'Illustrée', 'NV-HP', 2538);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (609, 'Noëlla', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 8859);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (739, 'Ruì', 'SK1N NATURAL SUNSCREEN SPF 20', 3382);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (387, 'Méline', 'Robaxin', 2279);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (899, 'Stévina', 'DEXTROSE', 1304);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (743, 'Simplifiés', 'Diphenhydramine HCl', 8755);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (535, 'Östen', 'Pollens - Trees, Mesquite, Prosopis juliflora', 5281);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (486, 'Fèi', 'Ibuprofen PM', 7725);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (654, 'Kallisté', 'OXYGEN', 5776);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (368, 'Almérinda', 'Daily Moisturizing', 7404);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (339, 'Esbjörn', 'sunmark', 2725);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (944, 'Laïla', 'Gas Relief', 9699);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (481, 'Angèle', 'Good Neighbor Pharmacy Sinus and Cold D', 4491);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (211, 'Marlène', 'Sunmark Nicotine', 3041);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (815, 'Marie-thérèse', 'Midol Complete', 2839);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (160, 'Océane', 'Neutrogena Naturals Acne Cleanser', 3363);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (789, 'Personnalisée', 'Losortan Potassium', 2656);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (879, 'Marylène', 'Pleo Reb', 8163);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (910, 'Mylène', 'Liver Drainage', 5823);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (584, 'Estève', 'Childrens Allergy', 2942);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (117, 'Naéva', 'Oxygen', 3443);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (625, 'Lyséa', 'Skin So Soft', 3133);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (150, 'Maïlis', 'Nicotine', 7715);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (478, 'Yú', 'A-METHAPRED', 1833);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (170, 'Athéna', 'Solarcaine cool aloe', 9457);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Laïla', 'GO TIME', 7980);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (747, 'Marie-ève', 'No7 Protect and Perfect Day Sunscreen Broad Spectrum SPF 15', 5657);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (312, 'Anaël', 'Procardia', 2149);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (668, 'Intéressant', 'Oxybutynin Chloride', 7272);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (141, 'Réservés', 'Atenolol', 3249);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (951, 'Aimée', 'Clarithromycin', 4480);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (598, 'Dà', 'Pancuronium Bromide', 7355);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (796, 'Loïs', 'Family Wellness Miconazole 3', 9132);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (141, 'Maï', 'Methylphenidate HCl Oral Solution', 8948);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (558, 'Angélique', 'Asparagus', 5004);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (146, 'Adèle', 'Veil Fluid Makeup Light Beige', 5440);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (104, 'Laurène', 'Tamsulosin Hydrochloride', 4644);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (224, 'Annotés', 'Pain Relief PM', 1473);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (228, 'Mén', 'Myrbetriq', 1076);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (623, 'Célia', 'Levoxyl', 1106);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (463, 'Börje', 'Normosol-R', 2689);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (542, 'Maéna', 'Keep The Peace Protect and Correct', 2397);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (142, 'Sòng', 'Cover Fx BB Gel Mattfying Anti-Blemish P Med-Deep', 7356);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (347, 'Mélinda', 'Herring', 9261);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (785, 'Médiamass', 'Ciprofloxacin', 4702);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (352, 'Bénédicte', 'Mens Rogaine', 2652);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (498, 'Michèle', 'City Sunscreen serum SPF 30', 5248);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (687, 'Mélia', 'Dicloxacillin Sodium', 1729);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (266, 'Ruò', 'lubricant and redness reliever', 4233);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (268, 'Hélène', 'Aggrenox', 1615);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (857, 'Mélissandre', 'Western Juniper Pollen', 6993);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (957, 'Agnès', 'Ofloxacin', 5869);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (870, 'Östen', 'Lovastatin', 7235);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (555, 'Naëlle', 'Metoprolol Tartrate', 7661);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (333, 'Léonie', 'Furosemide', 7935);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (941, 'Chloé', 'HEADACHE', 7548);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (189, 'Simplifiés', 'Soothe and Cool Moisture Guard', 6375);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (923, 'Styrbjörn', 'Renagel', 2784);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (750, 'Mégane', 'Maximum Strength', 4826);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (445, 'Géraldine', 'Dextromethorphan Hydrobromide and Promethazine Hydrochloride', 9841);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (628, 'Cécilia', 'ESIKA', 6026);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (655, 'Wá', 'Treatment Set TS332509', 9499);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (512, 'Néhémie', 'Theophylline', 5920);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (292, 'Illustrée', 'Eye Wash', 1870);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (107, 'Magdalène', 'Triple Antibiotic with Pain Relief', 4833);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (953, 'Ruì', 'Gabapentin', 7642);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (301, 'Inès', 'Coppertone Water Babies', 8368);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (435, 'Mélissandre', 'Sugar Maple', 3070);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (533, 'Adélie', 'Instant Hand Sanitizer Original With Aloe Vera And Vitamin E', 4407);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (516, 'Magdalène', 'AVONEX', 3647);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (742, 'Marie-josée', 'Clear Choice Out of Sight', 2399);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (371, 'Mén', 'Amlodipine Besylate and Benazepril Hydrochloride', 8166);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (252, 'Illustrée', 'Xylocaine', 2003);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (461, 'Cinéma', 'PDI Sani-HandsInstant Hand Sani', 4592);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (160, 'Annotée', 'CARTEOLOL HYDROCHLORIDE', 9229);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (474, 'Réservés', 'Lipitor', 4725);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (537, 'Táng', 'Antara', 8731);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (349, 'Lèi', 'DIARRHEA VOMITING', 6133);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (657, 'Styrbjörn', 'Ciprofloxacin', 4642);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (276, 'Andréa', 'ARTEMISIA ANNUA POLLEN', 1730);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (740, 'Danièle', 'LEVOTHYROXINE SODIUM', 4618);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (549, 'Nadège', 'Niaspan', 5876);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (942, 'Pélagie', 'Doxepin Hydrochloride', 7227);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (428, 'Gaétane', 'Remedy Zinc Skin Protectant', 3718);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (477, 'Lyséa', 'Methimazole', 9478);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (132, 'Almérinda', 'Health Mart Ibuprofen IB', 9307);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (721, 'Bérangère', 'PULLULARIA PULLULANS', 6205);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (107, 'Mårten', 'Perform', 8799);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (178, 'Mélia', 'DawnMist Antiperspirant Deodorant', 7627);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (180, 'Méghane', 'Imipramine Hydrochloride', 7904);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (614, 'Görel', 'safety coated aspirin', 3601);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (560, 'Frédérique', 'Antibacterial Hand Soap', 7322);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (107, 'Eliès', 'Pepper Tree Pollen', 2474);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (612, 'Cécile', 'Ziprasidone Hydrochloride', 3622);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (356, 'Mélanie', 'Western Family', 3033);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (499, 'Kallisté', 'Skin So Soft Bug Guard Plus IR3535', 6020);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (439, 'Béatrice', 'Ketorolac Tromethamine', 5982);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (828, 'Bérangère', 'Trandolapril', 3757);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (775, 'Aurélie', 'Tension Headache Relief', 4940);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (893, 'Marie-hélène', 'Sinusin', 5145);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (928, 'Gaétane', 'Lycopodium Kit Refill', 2135);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (821, 'Méng', 'Tretinoin', 4575);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (677, 'Judicaël', 'Cyanokit', 6458);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (666, 'Pò', 'Acyclovir', 9883);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (281, 'Anaïs', 'Critic Aid Clear AF', 4127);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (896, 'Béatrice', 'Coreg', 2455);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (800, 'Örjan', 'clearlax', 2778);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (266, 'Léandre', 'Dr. Scholls', 4355);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (216, 'Joséphine', 'Novana All-In-One One Step Perineal', 5157);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (210, 'Mylène', 'Zeel', 8207);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (911, 'Esbjörn', 'Ketoprofen', 3104);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (470, 'Anaëlle', 'Trazodone Hydrochloride', 5124);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (330, 'Camélia', 'Quality Choice Tolnaftate Antifungal', 2138);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (975, 'Göran', 'zinc oxide', 7999);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (299, 'Anaé', 'Tramadol Hydrochloride', 6219);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (960, 'Danièle', 'Clarithromycin', 2015);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (712, 'Yáo', 'Cefadroxil', 1321);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (429, 'Daphnée', 'SHISEIDO PERFECT REFINING FOUNDATION', 1162);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (928, 'Lèi', 'Kicking and Screaming', 6581);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (601, 'Cécilia', 'Berberis Quartz', 5463);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (986, 'Clémence', 'NATRUM MURIATICUM', 4081);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (148, 'Rébecca', 'Glandulae suprarenales 6 Special Order', 9039);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (312, 'Dà', 'Cenestin', 6077);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (281, 'Cloé', 'Alclometasone Dipropionate', 1780);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (333, 'Danièle', 'THE HISTORY OF WHOO GONGJINHYANG SEOL WHITENING SUN', 8441);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (314, 'Vénus', 'Mistletoe and Mint Antibacterial Foaming Hand Wash', 7100);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (498, 'Marie-ève', 'Tobramycin', 8962);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (153, 'Naëlle', 'Lactated Ringers', 9106);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (269, 'Sélène', 'SIMVASTATIN', 9764);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (918, 'André', 'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)', 3159);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (133, 'Marie-thérèse', 'PIMTREA', 9287);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (953, 'Kù', 'GREASEWOOD POLLEN', 1379);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (496, 'Méghane', 'Oxycodone Hydrochloride and Acetaminophen', 4675);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (378, 'Örjan', 'First Aid Double Antibiotic', 9461);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (454, 'Edmée', 'TobraDex', 5276);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (641, 'Aurélie', 'KENALOG-40', 1637);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (153, 'Zhì', 'Sword Fish', 7949);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (604, 'Mégane', 'Maximum Strength Mucus Relief Cold and SInus Max', 9031);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (877, 'Anaël', 'topcare pain and fever', 8709);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (101, 'Görel', 'HA2CG EVOLUTION', 6962);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (618, 'Clémentine', 'Megestrol Acetate', 2626);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (217, 'Jú', 'Home Health Psoriasis Medicated Scalp and Body Wash', 4203);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (976, 'Yénora', '7 Select Migraine Formula', 5434);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (449, 'Yè', 'Naproxen', 8107);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (941, 'Angèle', 'Valsartan and hydrochlorothiazide', 5128);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (264, 'Lauréna', 'Intervene Makeup SPF 15 Soft Porcelain', 3167);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (192, 'Hélène', 'Benazepril hydrochloride and hydrochlorothiazide', 2493);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (781, 'Eléa', 'Cefdinir', 2773);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (268, 'Eléonore', 'good neighbor pharmacy cold', 4835);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (349, 'Lài', 'temazepam', 4073);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (679, 'Réjane', 'Metronidazole', 9834);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (561, 'Célia', 'AMBROSIA TENUIFOLIA POLLEN', 2962);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (939, 'Zhì', 'Antiseptic Hand Cleansing Gel', 5232);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (650, 'Bérangère', 'Good Neighbor Pharmacy Cough DM ER', 8262);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (626, 'Mélanie', 'Neuro 3', 7608);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (149, 'Gaëlle', '2in1', 6894);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (877, 'Renée', 'Hemorrhoids Bruises', 4880);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (229, 'Torbjörn', 'Baclofen', 4856);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (792, 'Marlène', 'Neomycin and Polymyxin B Sulfates and Hydrocortisone', 6024);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (108, 'Cléopatre', 'Clotrimazole', 9491);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (210, 'Céline', 'VIDEX', 4655);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (917, 'Vénus', 'Rite Aid', 2186);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (366, 'Rachèle', 'Hand San', 7154);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (388, 'Andréa', 'Metformin Hydrochloride', 8251);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (497, 'Rachèle', 'Day Time', 1845);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (650, 'Frédérique', 'cold and flu', 8789);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (818, 'Andréa', 'GI Drainage', 1222);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (824, 'Laïla', 'Oxygen-Nitrogen Mixture', 1541);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (361, 'Edmée', 'Cover Fx Blemish Treatment Concealer P Medium', 3690);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (496, 'Loïs', 'Mucinex Fast-Max Day Time Severe Cold and Mucinex Fast-Max Night Time Cold and Flu', 1133);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (316, 'Noëlla', 'Cellular Laboratories De-Aging Sunscreen Broad Spectrum SPF 50 Plus', 5402);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (278, 'Marie-françoise', 'Gold Bond Pain Relieving Foot Roll On', 2321);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (593, 'Zhì', 'Acetaminophen, Diphenhydramine Hydrochloride, Phenylephrine Hydrochloride', 8256);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (684, 'Sòng', 'Crest 3D White', 6100);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (202, 'Dorothée', 'HIBERIX', 4636);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (399, 'Léone', 'Atripla', 6692);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (913, 'Céline', 'rexall anti diarrheal', 6476);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (214, 'Méryl', 'Fenoglide', 9700);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (488, 'Léonore', 'Standardized Grass Pollen, Ryegrass', 9044);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (579, 'Maïlis', 'Good Neighbor Pharmacy Hemorrhoidal', 2812);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (827, 'Agnès', 'Dipentum', 4679);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (527, 'André', 'PROMETHAZINE HYDROCHLORIDE', 5327);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (853, 'Réservés', 'Leader Original SPF 4 Lip Balm', 5589);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (785, 'Amélie', 'Lansoprazole', 8935);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (824, 'Léonore', 'Epi-Clenz Pure Instant Hand Antiseptic', 9870);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (551, 'Anaïs', 'OXYGEN', 6247);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (461, 'Annotée', 'risperidone', 2519);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (499, 'Andréa', 'Utah Juniper', 9154);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (736, 'Kuí', 'Triamcinolone Acetonide', 4070);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (740, 'Athéna', 'FIBER TABS', 4064);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (311, 'Intéressant', 'Captopril', 6319);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (702, 'Athéna', 'Isopropyl Alcohol', 9944);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (127, 'Sòng', 'COUMADIN', 7655);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (391, 'Clémentine', 'Trazodone Hydrochloride', 6407);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (376, 'Pénélope', 'Trandolapril', 8721);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (315, 'Laïla', 'Clonazepam', 7022);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (975, 'Lài', 'Zolpidem Tartrate', 7343);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (520, 'Gisèle', 'Alka-Seltzer Plus', 9670);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (761, 'Maïté', 'Valsartan and Hydrochlorothiazide', 3188);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (316, 'Cinéma', 'Sodium Acetate', 6284);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (874, 'Jú', 'Green Tussin SUGAR FREE', 2330);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (272, 'Táng', 'Pepper Tree Pollen', 6228);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (111, 'Méline', 'Phoma', 2449);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (102, 'Andréanne', 'Salsalate', 1124);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (783, 'Uò', 'Lithium Carbonate', 2567);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (134, 'Marie-josée', 'nifedipine', 4854);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (355, 'Görel', 'Rheumatoid Arthritis Pain Management', 9093);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (528, 'Dù', 'Imari Seduction', 9506);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (114, 'Adélie', 'Antiseptic Oral Cleanser', 6539);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (105, 'Aloïs', 'FOREVER LASTING ESSENTIAL EMULSION', 7500);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (293, 'Björn', 'Tacrolimus', 3946);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (383, 'Maïlys', 'Voltaren', 9232);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (416, 'Rachèle', 'SuperPlus Beblesh Balm Gold SPF25 PA 2Plus', 8563);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (561, 'Yáo', 'ZANAFLEX', 2068);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (819, 'Naéva', 'Hydrocortisone Acetate', 5345);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (750, 'Josée', 'Hongo Killer', 7883);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (790, 'Crééz', 'Heal Grief', 7462);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (692, 'Clélia', 'isosorbide mononitrate', 2418);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (724, 'Geneviève', 'Claravis', 6965);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (823, 'Yénora', 'Wart Freee', 6804);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (720, 'Léandre', 'TMC-A Anti Hairloss', 9079);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (859, 'Faîtes', 'LBEL divine lip gloss SPF 15', 9637);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (864, 'Loïc', 'Vancomycin Hydrochloride', 7628);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (652, 'Andréanne', 'meperidine hydrochloride', 1597);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (159, 'Märta', 'Eating Disorders', 8115);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (329, 'Pélagie', 'Oxygen', 2932);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (146, 'Lorène', 'Treatment Set TS350257', 6085);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Inès', 'Promethazine Hydrochloride', 3631);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (345, 'Mégane', 'Lamotrigine', 6959);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (134, 'Séverine', 'Smart Sense DayTime', 5666);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (867, 'Aloïs', 'Isosorbide Dinitrate', 8157);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (286, 'Pål', 'Equisetum cum sulfure tosta 6', 4241);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (315, 'Léandre', 'HAWAIIAN TROPIC', 9131);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (726, 'Angélique', 'BareMinerals', 6325);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Mylène', 'Plasbumin', 8876);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (432, 'Réservés', 'Rabeprazole Sodium', 6349);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (127, 'Åslög', 'CLARINS Skin Illusion SPF 10 Natural Radiance Foundation Tint 108', 6876);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (991, 'Méghane', 'CLOSE UP', 1557);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (372, 'Aloïs', 'biclora', 7360);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (852, 'Andrée', 'Prednisone', 1451);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (742, 'Maëline', 'Duloxetine', 9844);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (113, 'Fèi', 'Apis Mellifica Kit Refill', 7010);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (133, 'Réjane', 'LISINOPRIL', 4508);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (333, 'Yè', 'Cefuroxime axetil', 6310);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (741, 'Célia', 'Cystagon', 5725);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (933, 'Médiamass', 'Clozapine', 2462);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (871, 'Loïca', 'Filbert', 2550);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (524, 'Véronique', 'BANDAGE', 6344);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (676, 'Fèi', 'EUCALYPTUS BLUE GUM POLLEN', 1499);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (361, 'Anaïs', 'PERFECTION LUMIERE', 4354);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (205, 'Solène', 'APINOPHEN', 1625);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (623, 'Cinéma', 'Taclonex', 7808);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (533, 'Marylène', 'Sofskin Baby', 5186);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (803, 'Eugénie', 'Valproic Acid', 1033);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (959, 'Loïca', 'ShopRite Ni Calm', 5231);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (238, 'Marie-françoise', 'Primer Results Tinted Moisturizer SPF15 Golden Beige', 3120);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (316, 'Maïté', 'Tacrolimus', 3319);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (871, 'Athéna', 'Twynsta', 5896);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (283, 'Célia', 'Anti-Itch', 4786);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (200, 'Daphnée', 'Octreotide Acetate', 9906);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (233, 'Andréa', 'AMITRIPTYLINE HYDROCHLORIDE', 7750);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (861, 'Cléa', 'Alprazolam', 3555);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (479, 'Chloé', 'CLOZAPINE', 3146);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (197, 'Liè', 'Nortriptyline Hydrochloride', 7353);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (266, 'Chloé', 'PLATANUS OCCIDENTALIS POLLEN', 1471);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (254, 'Anaïs', 'Lysol', 2509);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (361, 'Régine', 'Green Olive', 8504);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (632, 'Fèi', 'Hydromorphone Hydrochloride', 3725);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (731, 'Miléna', 'Prednisolone', 5568);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (210, 'Estée', 'ANTIBACTERIAL', 2811);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (985, 'Vérane', 'HAWAIIAN Tropic', 4387);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (686, 'Pélagie', 'Doxazosin', 6582);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (384, 'Anaé', 'Paroxetine', 2406);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (489, 'Ruò', 'Lorazepam', 5226);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (641, 'Noémie', 'HAHNEMANN COLDS', 9041);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (922, 'Célestine', 'Escitalopram', 8669);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (384, 'Athéna', 'Cephalexin', 2497);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (247, 'Michèle', 'DAILY ESSENTIAL MOISTURISER', 5619);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (721, 'Naéva', 'Clearasil Daily Clear', 5649);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (678, 'Loïca', 'SWEET CLOVER POLLEN', 5197);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (774, 'Dorothée', 'Citalopram', 8502);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (756, 'Thérèsa', 'Eczema Rescue', 4327);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (951, 'Almérinda', 'Senna-Lax', 8656);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (126, 'Réservés', 'Anti-Fungal', 8803);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (273, 'Mélys', 'ROVECTIN', 9545);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (413, 'Aimée', 'ShopRite Ibuprofen', 2839);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (565, 'Marie-josée', 'Bupivacaine Hydrochloride and Epinephrine', 2814);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (493, 'Gaétane', 'Total Suncare Sunscreen SPF 70', 7498);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Lài', 'Belucie Luxury Timeless Golden Age Night', 5680);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (861, 'Eliès', 'Total White Brightening', 8018);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (340, 'Agnès', 'Tag Alder', 5097);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (666, 'Ruì', 'OsmoPrep', 2104);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (820, 'Inès', 'Hydrocodone Bitartrate and Ibuprofen', 1609);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (887, 'Maïté', 'Anti-Bacterial Hand', 2596);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (927, 'Liè', 'Premier Value Chest Congestion and cough releif', 9224);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (475, 'Maï', 'Albuterol Sulfate', 5340);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (820, 'Léonie', 'Regional Allergies Southern U.S.', 4204);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (795, 'Gwenaëlle', 'MEDIQUE I-PRIN', 1154);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (172, 'Régine', 'NICOTROL', 8245);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (722, 'Esbjörn', 'SINEMET', 2926);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (526, 'Marie-josée', 'SYNTHROID', 3612);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (107, 'Audréanne', 'Tramadol Hydrochloride', 3439);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (712, 'Océanne', 'Advanced Jellyfish Sting Kit', 4166);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (832, 'Garçon', 'Clarithromycin', 6154);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (416, 'Eloïse', 'SunScreen SPF30', 6350);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (305, 'Crééz', 'Morphine Sulfate', 4705);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (111, 'Mén', 'Acetaminophen PM', 2538);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (387, 'Mylène', 'Heparin Sodium', 8855);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (611, 'Mahélie', 'Too Faced BB Creme Complete Coverage Make-Up', 8928);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (653, 'Naéva', 'Daytime Cold and Flu Relief', 5657);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (139, 'Eloïse', 'Berry Scented Hand Sanitizer', 7392);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (174, 'Cléopatre', 'BANANA BOAT', 7181);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (281, 'Irène', 'Australian Gold', 2477);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (907, 'Håkan', 'Pravastatin Sodium', 5441);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (158, 'Stéphanie', '3M Avagard D', 8149);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (554, 'Miléna', 'Acne Medication 5', 9743);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (113, 'Hélèna', 'oxaprozin', 5643);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (711, 'Marie-noël', 'Omeprazole', 6079);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (227, 'Personnalisée', 'ESIKA HD COLOR HIGH DEFINITION COLOR SPF 20', 3808);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (617, 'Cléopatre', 'Kaletra', 7350);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (875, 'Marie-ève', 'Ranitidine', 9378);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (832, 'Eloïse', 'COMPRESSED GAS N.O.S.', 9705);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (375, 'Angèle', 'Coppertone Clearly Sheer For Sunny Days', 7753);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (693, 'Clémentine', 'NEURALGIA HEADACHE', 2123);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (351, 'Cléa', 'Artificial Tears', 2836);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (357, 'Judicaël', 'Pollens - Trees, Pine Mix', 7638);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (861, 'Andrée', 'V-COF', 8499);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (129, 'Mélinda', 'ZESTRIL', 9168);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (506, 'Eugénie', 'Pleo Oku', 5356);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (538, 'Léa', 'ShopRite Day Calm', 3763);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (713, 'Lorène', 'SMART SENSE', 9929);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (648, 'Joséphine', 'Olanzapine', 8647);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (299, 'Yáo', 'Silver Sulfadiazene', 2195);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (607, 'Esbjörn', 'Meloxicam', 6091);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (843, 'Alizée', 'Glyburide', 5658);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (905, 'Marie-noël', 'SOMA Prouri', 6863);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (663, 'Cléopatre', 'NITROGEN', 7931);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (664, 'Kallisté', 'Pampers Kandoo', 5107);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (491, 'Lorène', 'Cloves', 7783);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (412, 'Erwéi', 'WHEAT', 5554);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (427, 'Célia', 'CVS Pharmacy', 9046);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (901, 'Lén', 'ibuprofen pm', 4223);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (280, 'Marylène', 'Amlodipine Besylate', 1213);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (446, 'Méng', 'PreviDent', 1401);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (120, 'Anaël', 'Acarbose', 8170);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (190, 'Angèle', 'HEMORRHOID RELIEF', 7867);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (287, 'Séréna', 'Terbinafine', 5884);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (780, 'Wá', 'Thiothixene', 2246);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (685, 'Mahélie', 'Tirosint', 1444);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (723, 'Göran', 'Avon Elements', 7718);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (779, 'Hélène', 'Dantrium', 7651);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (387, 'Liè', 'Oxygen', 2912);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (784, 'Stévina', 'DIARRHEA VOMITING', 1698);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (711, 'Mén', 'Up and Up Anticavity Toothpaste Whitening', 6752);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (970, 'Andrée', 'Amoxicillin', 6672);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (572, 'Océane', 'Hydrocodone Bitartrate and Ibuprofen', 9138);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (166, 'Mégane', 'Bed Wetting', 1465);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (281, 'Naëlle', 'TopCare Milk of Magnesia', 6372);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (866, 'Lyséa', 'Verapamil Hydrochloride', 5461);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (742, 'Joséphine', 'Midazolam Hydrochloride', 7339);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (811, 'André', 'Lithium Carbonate', 6398);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (564, 'Annotée', 'THE HISTORY OF WHOO GONGJINHYANG SEOL WHITENING SUN', 2689);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (695, 'Laurélie', 'Cell to Cell Essence 70mL', 8957);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (830, 'Adèle', 'Allium cepa', 6945);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (192, 'Dafnée', 'Diastat', 2214);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (982, 'Mà', 'Epirubicin Hydrochloride', 6500);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (814, 'Anaëlle', 'Guanfacine Hydrochloride', 2232);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (914, 'Geneviève', 'Hydroxyzine Hydrochloride', 7070);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (549, 'Laurélie', 'Pollens - Trees, Willow, Black Salix nigra', 3390);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (815, 'Håkan', 'NEOMYCIN SULFATE', 6062);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (411, 'Lucrèce', 'Valsartan and Hydrochlorothiazide', 4333);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (223, 'Desirée', 'GlipizideER', 4283);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (165, 'Kévina', 'Dimenhydrinate', 9260);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (689, 'Séréna', 'Sanatos', 5119);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (290, 'Hélèna', 'Amoxicillin and Clavulanate Potassium', 7839);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (381, 'Pò', 'Mi Acid', 9700);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (106, 'Hélène', 'Oxygen', 4975);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (725, 'Mélinda', 'Estradiol', 9283);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (409, 'Anaël', 'Diabenex HP', 6252);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (614, 'Marlène', 'Diazepam', 9545);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (583, 'Börje', 'Gelato Topical Anesthetic', 3844);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (128, 'Måns', 'mint', 6243);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (146, 'Lyséa', 'Buspirone Hydrochloride', 6402);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (297, 'Desirée', 'Professional Therapy', 3831);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (646, 'Séréna', 'Whoo Gong Jin Hyang Jin Hae Yoon Sun', 1708);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (891, 'Estée', 'Hydrogen Peroxide', 6861);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (629, 'Illustrée', 'Viagra', 5506);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (595, 'Torbjörn', 'Hydrochlorothiazide', 2865);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (641, 'Maëline', 'SHOPKO TRIPLE ANTIBIOTIC PLUS', 9302);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (179, 'Erwéi', 'Trazodone Hydrochloride', 6449);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (244, 'Maïlys', 'GIGI ANESTHETIC NUMBING', 3677);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (877, 'Lóng', 'Potassium Phosphates', 3611);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (455, 'Mélina', 'triamcinolone acetonide', 4295);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (513, 'Ruò', 'Seaweed Cleansing', 8252);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (314, 'Pò', 'Amitriptyline Hydrochloride', 2009);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (179, 'Táng', 'Valacyclovir Hydrochloride', 7099);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (838, 'Agnès', 'Analpram Advanced', 1117);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (502, 'Åslög', 'Claritin', 3544);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (208, 'Françoise', 'ATORVASTATIN CALCIUM', 9099);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (865, 'Audréanne', 'Sotradecol', 8075);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (928, 'Céline', 'Skin Delight Mask Pack Plus', 5057);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (314, 'Cécile', 'Strazepam', 6232);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (194, 'Marylène', 'Ofloxacin', 3787);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (817, 'Méghane', 'smart sense allergy', 5292);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (446, 'Lén', 'GoodSense', 7507);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (870, 'Marylène', 'Pearl White', 8605);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (456, 'Eloïse', 'Telmisartan and Hydrochlorothiazide', 4919);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (738, 'Sòng', 'Heparin Sodium and Sodium Chloride', 3317);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (396, 'Léonie', 'OXYGEN', 3231);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (343, 'Styrbjörn', 'Clonazepam', 6175);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (239, 'Maïlys', 'Doxepin Hydrochloride', 3736);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (790, 'Maéna', 'Dove', 9191);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (930, 'Josée', 'Ciprofloxacin', 4992);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (617, 'Publicité', 'laura mercier tinted moisturizer Broad Spectrum SPF 20 Sunscreen Lightweight Flawless Coverage OCHRE', 4973);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (455, 'Personnalisée', 'Clarithromycin', 1029);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (225, 'Fèi', 'Softlips Chocolate Bunny', 9996);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (691, 'Marie-josée', 'Everyday Facial Moisturizer And Sunscreen SPF 20', 5252);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (667, 'Clélia', 'Hydrocortisone and Acetic Acid', 5685);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (979, 'Séréna', 'Antiseptic Mouth Rinse', 4459);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (604, 'Joséphine', 'CD DIOR PRESTIGE WHITE COLLECTION SATIN BRIGHTENING UVB BASE WITH SUNSCREEN SPF 50', 9698);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (180, 'Gwenaëlle', 'NATURAL SUN AQ TOTAL ANTI-AGING ESSENCE SUN', 6769);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (902, 'Zoé', 'Humulin', 5976);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (927, 'Thérèsa', 'Obao Men Audaz', 6619);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (160, 'Tú', 'equate athletes foot', 6624);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (715, 'Léone', 'Intercellular Detox', 5999);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (538, 'Angèle', 'Milk of Magnesia Mint', 6208);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (629, 'Gaétane', 'Nasal', 1005);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (693, 'Joséphine', 'Aetna Callus Remover', 7126);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (279, 'Cunégonde', 'Glyburide', 6120);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (344, 'Maëlle', 'Dr Smiths Diaper Rash', 4376);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (734, 'Cunégonde', 'Treatment Set TS351314', 5397);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (136, 'Irène', 'Metronidazole', 5574);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (300, 'Personnalisée', 'anti itch', 4228);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (879, 'Annotée', 'Pure Kleen', 8225);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (351, 'Cécilia', 'Carbidopa, Levodopa and Entacapone', 3098);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (324, 'Nadège', 'Gabapentin', 4573);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (105, 'Erwéi', 'Lamotrigine', 2221);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (536, 'Irène', 'cephalexin', 6264);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (563, 'Kévina', 'Verapamil', 7379);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (961, 'Åsa', 'Aveeno Active Naturals Skin Relief Calming', 1223);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (323, 'Crééz', 'BETHANECHOL CHLORIDE', 4265);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (115, 'Clémentine', 'antifungal', 7991);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (231, 'Béatrice', 'Cyclobenzaprine Hydrochloride', 8068);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (938, 'Kévina', 'Queen Palm', 4850);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (782, 'Kévina', 'Cheongin Haejanghwan', 4179);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (390, 'Illustrée', 'Sun Care', 8327);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (658, 'Mylène', 'Xartemis', 4442);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (143, 'Mégane', 'Shagbark Hickory', 7667);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (381, 'Célia', 'Levetiracetam', 3087);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (604, 'Aloïs', 'Cortomycin', 3460);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (755, 'Tú', 'Molds, Penicillium Mix', 4469);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (863, 'Anaé', 'VENLAFAXINE HYDROCHLORIDE', 5703);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (460, 'Gisèle', 'Betamethasone Dipropionate', 5425);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (917, 'André', 'I 131 Mini', 2467);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (431, 'Lén', 'Baczol Cold Medicine', 2860);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (848, 'Mélys', 'COUMADIN', 1282);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (553, 'Inès', 'Dove', 6279);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (487, 'Edmée', 'MK BZK Antiseptic Towelette Sterile', 2891);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (354, 'Thérèse', 'FUSARIUM OXYSPORUM VASINFECTUM', 9868);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (996, 'Mégane', 'Cutiecaine', 6335);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (637, 'Cinéma', 'GenTeal', 2306);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (266, 'Marie-hélène', 'CareOne Antacid', 3827);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (917, 'Séverine', 'Clarithromycin', 1749);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (367, 'Réjane', 'PEA', 9131);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (110, 'Anaël', 'Puralube', 4743);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (882, 'Crééz', 'Dermasil Sensitive', 6631);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (620, 'Stévina', 'Healing After Surgery', 2783);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (223, 'Renée', 'childrens ibuprofen', 8126);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (131, 'Régine', 'Recombinate', 9252);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (885, 'Bérengère', 'Enalapril Maleate', 5675);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (233, 'Mélodie', 'Maracuja Miracle Foundation 12-Hour Foundation Broad Spectrum SPF 15 Sunscreen', 2579);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (132, 'Eugénie', 'Alba Sunblock Natural Kids SPF 45', 6983);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (654, 'Hélèna', 'Tinted Moisturizer', 8475);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (510, 'Vérane', 'KEEPAN A', 5723);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (297, 'Gaëlle', 'Cyclease Cramp', 3613);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (426, 'Lorène', 'Equate Menthol extra strength', 2867);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (782, 'André', 'Bio Rock Water', 6174);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Kallisté', 'Purminerals 4 in 1 Makeup SPF 15 Deepest', 2123);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (522, 'Maïlys', 'Lorazepam', 3449);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (600, 'Görel', 'Flounder', 8072);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (265, 'Cloé', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 8267);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (263, 'Béatrice', 'Wal itin D', 8124);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (630, 'Marie-françoise', 'ERYTHROMYCIN ETHYLSUCCINATE', 2054);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (660, 'Méghane', 'Bisoprolol Fumarate', 5336);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (278, 'Bécassine', 'WellPatch Backache Pain Relief', 1750);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (313, 'Björn', 'Pioglitazone', 8091);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (402, 'Camélia', 'Benztropine Mesylate', 7082);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (527, 'Maéna', 'Albuterol Sulfate', 3818);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (983, 'Maëline', 'Cetirizine hydrochloride', 6668);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (707, 'Östen', 'ROBITUSSIN PEAK COLD MAXIMUM STRENGTH COUGH PLUS CHEST CONGESTION DM', 6712);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (938, 'Aimée', 'Good Sense Ibuprofen', 1742);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (556, 'Aimée', 'Colchicum e tub. 4 Special Order', 2355);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (501, 'Stéphanie', 'Givenchy TEINT COUTURE Long Wearing Fluid Foundation with Sunscreen Broad Spectrum SPF 20 ELEGANT PORCELAIN', 2605);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (631, 'Hélèna', 'Metoprolol Tartrate', 6800);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (290, 'Eloïse', 'Blackberry', 9096);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (785, 'André', 'Sore Throat Right Side', 9104);
insert into persons_in_gothenburg (id, first_name, last_name, person_number) values (251, 'Adèle', 'topcare antacid calcium', 8865);
