create table yrgo_records (
	person_number INT,
	student_name TEXT,
	student_address VARCHAR(50)
);
insert into yrgo_records (person_number, student_name, student_address) values (8641, 'mus vivamus', '28 Hanover Point');
insert into yrgo_records (person_number, student_name, student_address) values (5094, 'mi integer', '334 Hansons Way');
insert into yrgo_records (person_number, student_name, student_address) values (5119, 'amet cursus', '99 Crowley Road');
insert into yrgo_records (person_number, student_name, student_address) values (1894, 'eget massa', '3 Hintze Hill');
insert into yrgo_records (person_number, student_name, student_address) values (1741, 'at velit', '167 Sloan Center');
insert into yrgo_records (person_number, student_name, student_address) values (8344, 'sit amet', '17266 Clyde Gallagher Center');
insert into yrgo_records (person_number, student_name, student_address) values (6599, 'accumsan odio', '25 Vahlen Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (2153, 'auctor gravida', '88 Aberg Circle');
insert into yrgo_records (person_number, student_name, student_address) values (8714, 'consequat lectus', '65182 Reinke Street');
insert into yrgo_records (person_number, student_name, student_address) values (5265, 'sapien arcu', '52 Hoard Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (8415, 'augue vestibulum', '0 Dixon Street');
insert into yrgo_records (person_number, student_name, student_address) values (4620, 'congue elementum', '80300 Leroy Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (8956, 'dis parturient', '52 Fulton Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9787, 'pede venenatis', '29 Bonner Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (3799, 'elit proin', '46574 Becker Place');
insert into yrgo_records (person_number, student_name, student_address) values (9018, 'eros suspendisse', '47 Melrose Pass');
insert into yrgo_records (person_number, student_name, student_address) values (1290, 'hac habitasse', '867 Delladonna Pass');
insert into yrgo_records (person_number, student_name, student_address) values (7929, 'sed vestibulum', '5029 Oakridge Trail');
insert into yrgo_records (person_number, student_name, student_address) values (8181, 'aliquam quis', '8942 Petterle Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (5527, 'dui vel', '06520 Monument Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4245, 'tincidunt eu', '8469 Oneill Junction');
insert into yrgo_records (person_number, student_name, student_address) values (1775, 'ac nulla', '2 Cardinal Way');
insert into yrgo_records (person_number, student_name, student_address) values (6888, 'in est', '77 Linden Alley');
insert into yrgo_records (person_number, student_name, student_address) values (3324, 'sapien sapien', '34 Novick Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1253, 'aliquam convallis', '44205 Glendale Park');
insert into yrgo_records (person_number, student_name, student_address) values (4453, 'molestie sed', '296 Dorton Lane');
insert into yrgo_records (person_number, student_name, student_address) values (3967, 'magna vulputate', '97 Anniversary Court');
insert into yrgo_records (person_number, student_name, student_address) values (2208, 'vel accumsan', '0529 Service Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (8783, 'justo morbi', '10511 Oak Valley Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (7500, 'fusce consequat', '083 Dryden Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (7808, 'pede venenatis', '99 Spaight Lane');
insert into yrgo_records (person_number, student_name, student_address) values (3380, 'enim lorem', '06 Hermina Junction');
insert into yrgo_records (person_number, student_name, student_address) values (4561, 'quis augue', '56235 East Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1887, 'nec nisi', '7 Lien Road');
insert into yrgo_records (person_number, student_name, student_address) values (7940, 'nunc rhoncus', '17074 Mayer Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1166, 'vulputate elementum', '1994 Sunfield Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1496, 'turpis a', '05903 Burning Wood Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (5048, 'dapibus at', '10410 Sutteridge Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (6640, 'nunc viverra', '21 Dryden Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (6847, 'in magna', '60950 Parkside Park');
insert into yrgo_records (person_number, student_name, student_address) values (8079, 'felis ut', '50 East Way');
insert into yrgo_records (person_number, student_name, student_address) values (7046, 'ante ipsum', '49 Columbus Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9318, 'nisl duis', '94131 Ramsey Way');
insert into yrgo_records (person_number, student_name, student_address) values (2906, 'tortor eu', '33702 Orin Junction');
insert into yrgo_records (person_number, student_name, student_address) values (1560, 'laoreet ut', '2489 Boyd Road');
insert into yrgo_records (person_number, student_name, student_address) values (1993, 'cubilia curae', '7378 Anthes Park');
insert into yrgo_records (person_number, student_name, student_address) values (9651, 'sagittis nam', '09 Jenna Park');
insert into yrgo_records (person_number, student_name, student_address) values (8062, 'curabitur at', '1 Ohio Court');
insert into yrgo_records (person_number, student_name, student_address) values (4137, 'integer aliquet', '7 Arizona Hill');
insert into yrgo_records (person_number, student_name, student_address) values (5311, 'at dolor', '603 2nd Court');
insert into yrgo_records (person_number, student_name, student_address) values (4134, 'orci mauris', '35 Declaration Way');
insert into yrgo_records (person_number, student_name, student_address) values (2216, 'imperdiet et', '8 Burrows Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (9111, 'enim lorem', '5078 Marquette Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4295, 'accumsan tortor', '1199 Derek Court');
insert into yrgo_records (person_number, student_name, student_address) values (1285, 'maecenas tristique', '53272 Claremont Place');
insert into yrgo_records (person_number, student_name, student_address) values (4320, 'aliquam non', '1 Crowley Place');
insert into yrgo_records (person_number, student_name, student_address) values (5192, 'amet diam', '782 Mcbride Junction');
insert into yrgo_records (person_number, student_name, student_address) values (1008, 'sem fusce', '39 Drewry Park');
insert into yrgo_records (person_number, student_name, student_address) values (5098, 'nam nulla', '99 Killdeer Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (4618, 'pede posuere', '9 New Castle Point');
insert into yrgo_records (person_number, student_name, student_address) values (1520, 'lobortis vel', '1057 Harper Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1690, 'nisl duis', '097 Arrowood Lane');
insert into yrgo_records (person_number, student_name, student_address) values (4040, 'ligula sit', '8551 Heffernan Alley');
insert into yrgo_records (person_number, student_name, student_address) values (3214, 'justo morbi', '4 Independence Road');
insert into yrgo_records (person_number, student_name, student_address) values (3389, 'nulla tellus', '41 Darwin Center');
insert into yrgo_records (person_number, student_name, student_address) values (1913, 'porttitor id', '421 Golf View Lane');
insert into yrgo_records (person_number, student_name, student_address) values (6216, 'iaculis congue', '02059 Rieder Alley');
insert into yrgo_records (person_number, student_name, student_address) values (4723, 'elit proin', '128 Cambridge Trail');
insert into yrgo_records (person_number, student_name, student_address) values (2485, 'rhoncus dui', '82901 Fulton Junction');
insert into yrgo_records (person_number, student_name, student_address) values (5327, 'primis in', '20396 Briar Crest Way');
insert into yrgo_records (person_number, student_name, student_address) values (7001, 'et magnis', '9 Judy Way');
insert into yrgo_records (person_number, student_name, student_address) values (3841, 'non velit', '09 Northland Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2556, 'nunc donec', '0 6th Place');
insert into yrgo_records (person_number, student_name, student_address) values (9280, 'imperdiet et', '32 Emmet Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9422, 'quis lectus', '9405 Rusk Trail');
insert into yrgo_records (person_number, student_name, student_address) values (7121, 'a suscipit', '3502 Hudson Way');
insert into yrgo_records (person_number, student_name, student_address) values (6707, 'nulla suspendisse', '268 Bunting Street');
insert into yrgo_records (person_number, student_name, student_address) values (3881, 'sed justo', '9 Almo Lane');
insert into yrgo_records (person_number, student_name, student_address) values (8281, 'nam tristique', '646 Lunder Drive');
insert into yrgo_records (person_number, student_name, student_address) values (2433, 'id lobortis', '426 Donald Street');
insert into yrgo_records (person_number, student_name, student_address) values (5159, 'in tempor', '61 Packers Trail');
insert into yrgo_records (person_number, student_name, student_address) values (9254, 'augue luctus', '38340 Mallory Way');
insert into yrgo_records (person_number, student_name, student_address) values (2713, 'morbi quis', '443 Hazelcrest Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (4081, 'porttitor lacus', '2 Darwin Hill');
insert into yrgo_records (person_number, student_name, student_address) values (8096, 'non interdum', '21113 Nevada Center');
insert into yrgo_records (person_number, student_name, student_address) values (6259, 'sed sagittis', '7 7th Pass');
insert into yrgo_records (person_number, student_name, student_address) values (3418, 'lacinia sapien', '1 Sutherland Road');
insert into yrgo_records (person_number, student_name, student_address) values (2773, 'eros elementum', '5751 Arizona Park');
insert into yrgo_records (person_number, student_name, student_address) values (7788, 'turpis enim', '1630 Little Fleur Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1496, 'lacus curabitur', '59144 Sherman Pass');
insert into yrgo_records (person_number, student_name, student_address) values (4797, 'sit amet', '129 Scofield Road');
insert into yrgo_records (person_number, student_name, student_address) values (1483, 'duis mattis', '193 Sycamore Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (6262, 'montes nascetur', '651 Roxbury Point');
insert into yrgo_records (person_number, student_name, student_address) values (2666, 'laoreet ut', '1340 Magdeline Park');
insert into yrgo_records (person_number, student_name, student_address) values (5519, 'lacus curabitur', '156 Westport Way');
insert into yrgo_records (person_number, student_name, student_address) values (2083, 'commodo vulputate', '0 Rutledge Trail');
insert into yrgo_records (person_number, student_name, student_address) values (6334, 'nulla integer', '236 Basil Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (8112, 'duis faucibus', '5771 Shoshone Hill');
insert into yrgo_records (person_number, student_name, student_address) values (6355, 'bibendum morbi', '44502 Badeau Way');
insert into yrgo_records (person_number, student_name, student_address) values (7720, 'in lacus', '3622 New Castle Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (6507, 'nec nisi', '106 Veith Center');
insert into yrgo_records (person_number, student_name, student_address) values (5191, 'dis parturient', '0 Kenwood Street');
insert into yrgo_records (person_number, student_name, student_address) values (1399, 'venenatis turpis', '233 Ryan Court');
insert into yrgo_records (person_number, student_name, student_address) values (8175, 'accumsan tortor', '55196 Jana Street');
insert into yrgo_records (person_number, student_name, student_address) values (5551, 'tristique tortor', '02644 Vidon Trail');
insert into yrgo_records (person_number, student_name, student_address) values (6789, 'nulla ut', '487 Crescent Oaks Way');
insert into yrgo_records (person_number, student_name, student_address) values (6978, 'in est', '6288 Kingsford Hill');
insert into yrgo_records (person_number, student_name, student_address) values (8872, 'integer non', '25976 Superior Lane');
insert into yrgo_records (person_number, student_name, student_address) values (4605, 'tellus nisi', '60 Clemons Hill');
insert into yrgo_records (person_number, student_name, student_address) values (7158, 'non interdum', '85089 Hovde Road');
insert into yrgo_records (person_number, student_name, student_address) values (3431, 'pellentesque at', '23559 Del Sol Circle');
insert into yrgo_records (person_number, student_name, student_address) values (3842, 'et commodo', '12 Lotheville Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (1830, 'cursus vestibulum', '563 Northwestern Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2017, 'faucibus cursus', '93 Northland Circle');
insert into yrgo_records (person_number, student_name, student_address) values (3546, 'mauris sit', '5746 Lawn Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (9894, 'aenean lectus', '4107 Oakridge Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (9483, 'viverra eget', '6310 Judy Drive');
insert into yrgo_records (person_number, student_name, student_address) values (4250, 'luctus et', '9 3rd Pass');
insert into yrgo_records (person_number, student_name, student_address) values (7662, 'duis bibendum', '324 Golf View Court');
insert into yrgo_records (person_number, student_name, student_address) values (2484, 'scelerisque mauris', '6094 Melvin Park');
insert into yrgo_records (person_number, student_name, student_address) values (1988, 'condimentum curabitur', '0418 Crescent Oaks Point');
insert into yrgo_records (person_number, student_name, student_address) values (2828, 'nibh quisque', '99344 Huxley Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (2155, 'sollicitudin ut', '512 Service Park');
insert into yrgo_records (person_number, student_name, student_address) values (2211, 'non ligula', '7 Ryan Junction');
insert into yrgo_records (person_number, student_name, student_address) values (4328, 'diam id', '56 Artisan Street');
insert into yrgo_records (person_number, student_name, student_address) values (8146, 'sem mauris', '4490 Forest Dale Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (5893, 'consectetuer eget', '454 Artisan Park');
insert into yrgo_records (person_number, student_name, student_address) values (3500, 'mauris ullamcorper', '7 Pennsylvania Road');
insert into yrgo_records (person_number, student_name, student_address) values (7026, 'erat nulla', '5823 Brown Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1228, 'luctus et', '51 Westerfield Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (2471, 'vitae quam', '70 Hudson Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (7767, 'lacus at', '59 Miller Street');
insert into yrgo_records (person_number, student_name, student_address) values (2965, 'libero nullam', '7 Killdeer Point');
insert into yrgo_records (person_number, student_name, student_address) values (2776, 'hac habitasse', '19 Mayfield Way');
insert into yrgo_records (person_number, student_name, student_address) values (1964, 'libero ut', '7621 Northfield Street');
insert into yrgo_records (person_number, student_name, student_address) values (3228, 'fusce lacus', '0 Coleman Circle');
insert into yrgo_records (person_number, student_name, student_address) values (8968, 'massa id', '13335 John Wall Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7669, 'erat fermentum', '68681 Quincy Court');
insert into yrgo_records (person_number, student_name, student_address) values (8384, 'tempor convallis', '7696 Gina Point');
insert into yrgo_records (person_number, student_name, student_address) values (4362, 'fusce posuere', '67447 Prairieview Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (7662, 'vestibulum aliquet', '818 Cherokee Circle');
insert into yrgo_records (person_number, student_name, student_address) values (2655, 'fusce lacus', '391 Brickson Park Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (3057, 'aliquam augue', '31310 Fordem Place');
insert into yrgo_records (person_number, student_name, student_address) values (5433, 'blandit non', '9175 Bunker Hill Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (5508, 'eget tincidunt', '76257 Buhler Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (9549, 'justo sollicitudin', '89 Bonner Park');
insert into yrgo_records (person_number, student_name, student_address) values (4326, 'lobortis est', '918 Rowland Way');
insert into yrgo_records (person_number, student_name, student_address) values (8530, 'sapien varius', '8688 Sycamore Center');
insert into yrgo_records (person_number, student_name, student_address) values (3533, 'hendrerit at', '1 Vahlen Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (8773, 'non velit', '0552 Birchwood Pass');
insert into yrgo_records (person_number, student_name, student_address) values (5586, 'molestie hendrerit', '123 Dorton Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (8711, 'sollicitudin ut', '256 Pepper Wood Way');
insert into yrgo_records (person_number, student_name, student_address) values (6870, 'ultrices mattis', '4226 Annamark Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1450, 'tortor sollicitudin', '37 Laurel Alley');
insert into yrgo_records (person_number, student_name, student_address) values (7370, 'ac consequat', '417 Algoma Junction');
insert into yrgo_records (person_number, student_name, student_address) values (5862, 'vestibulum ante', '6799 Vidon Circle');
insert into yrgo_records (person_number, student_name, student_address) values (1334, 'tempor convallis', '09653 Russell Street');
insert into yrgo_records (person_number, student_name, student_address) values (4290, 'vestibulum eget', '069 Roxbury Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4004, 'ante vestibulum', '8914 Redwing Circle');
insert into yrgo_records (person_number, student_name, student_address) values (2064, 'dapibus nulla', '36582 Coolidge Hill');
insert into yrgo_records (person_number, student_name, student_address) values (6434, 'nisi at', '6 Fairfield Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1814, 'donec dapibus', '2224 Park Meadow Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (2614, 'in hac', '950 Lakeland Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (7190, 'nam nulla', '60 Arizona Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1671, 'hac habitasse', '232 Butterfield Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (6710, 'velit vivamus', '494 Emmet Hill');
insert into yrgo_records (person_number, student_name, student_address) values (1456, 'bibendum felis', '2663 Reinke Trail');
insert into yrgo_records (person_number, student_name, student_address) values (3867, 'quam nec', '05 Fuller Trail');
insert into yrgo_records (person_number, student_name, student_address) values (4334, 'nulla ac', '8350 Warner Junction');
insert into yrgo_records (person_number, student_name, student_address) values (6834, 'blandit mi', '7 Ronald Regan Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (7255, 'ut dolor', '08480 Linden Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (3032, 'sapien cum', '281 Heath Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (7406, 'dui vel', '3560 Nobel Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1267, 'vulputate elementum', '19 Evergreen Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1213, 'vivamus vestibulum', '0 Orin Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1412, 'adipiscing molestie', '8693 Di Loreto Road');
insert into yrgo_records (person_number, student_name, student_address) values (2693, 'risus dapibus', '46180 Larry Park');
insert into yrgo_records (person_number, student_name, student_address) values (5009, 'sit amet', '6 Sutherland Court');
insert into yrgo_records (person_number, student_name, student_address) values (8911, 'neque aenean', '1 Novick Lane');
insert into yrgo_records (person_number, student_name, student_address) values (2149, 'curae nulla', '90818 Cherokee Drive');
insert into yrgo_records (person_number, student_name, student_address) values (4323, 'hac habitasse', '1 Dennis Park');
insert into yrgo_records (person_number, student_name, student_address) values (7974, 'eget eleifend', '0 Forster Point');
insert into yrgo_records (person_number, student_name, student_address) values (5355, 'scelerisque mauris', '216 Fallview Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (1996, 'primis in', '3 Reinke Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (7159, 'ridiculus mus', '28557 Dryden Road');
insert into yrgo_records (person_number, student_name, student_address) values (3074, 'maecenas ut', '781 Maple Wood Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2810, 'amet eleifend', '254 Sheridan Center');
insert into yrgo_records (person_number, student_name, student_address) values (2423, 'lectus vestibulum', '645 Shoshone Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1736, 'sollicitudin vitae', '469 Lerdahl Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (2037, 'placerat ante', '9 Springs Way');
insert into yrgo_records (person_number, student_name, student_address) values (5051, 'lacus at', '93 Vidon Circle');
insert into yrgo_records (person_number, student_name, student_address) values (4821, 'tellus in', '35520 Esch Way');
insert into yrgo_records (person_number, student_name, student_address) values (5379, 'velit id', '268 Gerald Court');
insert into yrgo_records (person_number, student_name, student_address) values (6400, 'nisl aenean', '4725 Almo Way');
insert into yrgo_records (person_number, student_name, student_address) values (7647, 'magna ac', '47423 Farwell Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (4591, 'elementum in', '5 7th Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7214, 'nisi eu', '33 Mcguire Center');
insert into yrgo_records (person_number, student_name, student_address) values (7820, 'lacinia nisi', '2 Manufacturers Circle');
insert into yrgo_records (person_number, student_name, student_address) values (3197, 'in hac', '25006 Harper Center');
insert into yrgo_records (person_number, student_name, student_address) values (3211, 'lobortis vel', '808 Lawn Lane');
insert into yrgo_records (person_number, student_name, student_address) values (5423, 'erat eros', '578 Morrow Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1547, 'libero rutrum', '780 5th Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (7853, 'vitae mattis', '0255 Duke Trail');
insert into yrgo_records (person_number, student_name, student_address) values (7985, 'at nibh', '5868 Bartillon Junction');
insert into yrgo_records (person_number, student_name, student_address) values (6360, 'habitasse platea', '71 Cardinal Hill');
insert into yrgo_records (person_number, student_name, student_address) values (6743, 'ac diam', '32 Lunder Alley');
insert into yrgo_records (person_number, student_name, student_address) values (1947, 'odio elementum', '7804 Schmedeman Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (8465, 'vestibulum eget', '26 Oak Valley Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (5730, 'amet sapien', '1535 Del Mar Circle');
insert into yrgo_records (person_number, student_name, student_address) values (6643, 'maecenas tincidunt', '6127 Waubesa Place');
insert into yrgo_records (person_number, student_name, student_address) values (2912, 'pretium nisl', '5 Summerview Park');
insert into yrgo_records (person_number, student_name, student_address) values (7559, 'sit amet', '550 Monument Drive');
insert into yrgo_records (person_number, student_name, student_address) values (6291, 'rhoncus mauris', '06442 7th Park');
insert into yrgo_records (person_number, student_name, student_address) values (3179, 'lacus at', '762 Vidon Circle');
insert into yrgo_records (person_number, student_name, student_address) values (1390, 'curae nulla', '7 Bayside Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (6369, 'erat curabitur', '02 Twin Pines Way');
insert into yrgo_records (person_number, student_name, student_address) values (1052, 'pede ac', '0464 Towne Place');
insert into yrgo_records (person_number, student_name, student_address) values (5901, 'massa quis', '288 Farwell Point');
insert into yrgo_records (person_number, student_name, student_address) values (3760, 'tincidunt eget', '70538 Logan Alley');
insert into yrgo_records (person_number, student_name, student_address) values (8799, 'aliquet massa', '55393 Arkansas Road');
insert into yrgo_records (person_number, student_name, student_address) values (2664, 'pede morbi', '5847 Menomonie Alley');
insert into yrgo_records (person_number, student_name, student_address) values (3899, 'consequat lectus', '76 Rowland Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (6555, 'lorem id', '589 Springview Alley');
insert into yrgo_records (person_number, student_name, student_address) values (3923, 'phasellus in', '43 Upham Road');
insert into yrgo_records (person_number, student_name, student_address) values (4931, 'erat vestibulum', '1 Norway Maple Drive');
insert into yrgo_records (person_number, student_name, student_address) values (9694, 'lacus at', '38557 Waubesa Street');
insert into yrgo_records (person_number, student_name, student_address) values (7277, 'non mattis', '21557 Mosinee Drive');
insert into yrgo_records (person_number, student_name, student_address) values (4663, 'mauris eget', '5 Corscot Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7865, 'felis eu', '9363 Helena Road');
insert into yrgo_records (person_number, student_name, student_address) values (8556, 'tempus semper', '74 Dixon Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (9465, 'morbi ut', '016 Artisan Circle');
insert into yrgo_records (person_number, student_name, student_address) values (7218, 'in quam', '494 Buell Place');
insert into yrgo_records (person_number, student_name, student_address) values (8891, 'consequat metus', '44 Farwell Place');
insert into yrgo_records (person_number, student_name, student_address) values (3001, 'lobortis vel', '41 Vermont Place');
insert into yrgo_records (person_number, student_name, student_address) values (5622, 'lectus vestibulum', '4890 Prairieview Street');
insert into yrgo_records (person_number, student_name, student_address) values (5818, 'sed lacus', '7463 Glendale Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (3419, 'morbi porttitor', '168 Reindahl Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (2561, 'posuere cubilia', '77876 Washington Place');
insert into yrgo_records (person_number, student_name, student_address) values (6065, 'ipsum aliquam', '8128 Hooker Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (6021, 'nisl nunc', '92596 Butterfield Court');
insert into yrgo_records (person_number, student_name, student_address) values (5584, 'posuere metus', '9668 Longview Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (2002, 'eu tincidunt', '35 Artisan Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (9332, 'justo in', '22829 Hauk Point');
insert into yrgo_records (person_number, student_name, student_address) values (9103, 'vestibulum ante', '65 Old Gate Drive');
insert into yrgo_records (person_number, student_name, student_address) values (9275, 'id ligula', '264 Ridgeview Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2527, 'erat nulla', '67817 Vermont Court');
insert into yrgo_records (person_number, student_name, student_address) values (9173, 'morbi a', '75 Dapin Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1257, 'etiam faucibus', '9848 Erie Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (5238, 'convallis nunc', '82 Bluestem Junction');
insert into yrgo_records (person_number, student_name, student_address) values (3958, 'vestibulum sit', '7 American Ash Way');
insert into yrgo_records (person_number, student_name, student_address) values (6315, 'penatibus et', '6051 Northview Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (9063, 'id sapien', '922 Fallview Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (2718, 'orci luctus', '10 Saint Paul Drive');
insert into yrgo_records (person_number, student_name, student_address) values (5068, 'pellentesque ultrices', '02197 Pierstorff Trail');
insert into yrgo_records (person_number, student_name, student_address) values (9152, 'mattis pulvinar', '1666 Summit Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (2192, 'pede justo', '7 Westridge Park');
insert into yrgo_records (person_number, student_name, student_address) values (7191, 'eget nunc', '1647 Elmside Place');
insert into yrgo_records (person_number, student_name, student_address) values (3352, 'luctus nec', '2469 Eastwood Way');
insert into yrgo_records (person_number, student_name, student_address) values (6999, 'id consequat', '1 Glendale Alley');
insert into yrgo_records (person_number, student_name, student_address) values (4961, 'amet lobortis', '54156 Luster Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (2655, 'sit amet', '246 Forest Dale Road');
insert into yrgo_records (person_number, student_name, student_address) values (4077, 'nulla ut', '48 Vidon Pass');
insert into yrgo_records (person_number, student_name, student_address) values (7899, 'justo in', '0 Novick Point');
insert into yrgo_records (person_number, student_name, student_address) values (5190, 'mattis egestas', '980 Lakewood Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1234, 'platea dictumst', '5181 Manley Way');
insert into yrgo_records (person_number, student_name, student_address) values (8163, 'iaculis congue', '8873 Red Cloud Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (8217, 'eget vulputate', '8583 Larry Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (7830, 'luctus ultricies', '5 Granby Road');
insert into yrgo_records (person_number, student_name, student_address) values (9534, 'quis orci', '6 Melby Drive');
insert into yrgo_records (person_number, student_name, student_address) values (9564, 'mauris lacinia', '08825 Glendale Lane');
insert into yrgo_records (person_number, student_name, student_address) values (3718, 'pellentesque viverra', '7 Moland Drive');
insert into yrgo_records (person_number, student_name, student_address) values (5130, 'dis parturient', '6227 Golf Circle');
insert into yrgo_records (person_number, student_name, student_address) values (3457, 'eget eros', '193 Elmside Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7878, 'amet sem', '85 Mcguire Trail');
insert into yrgo_records (person_number, student_name, student_address) values (9192, 'dapibus at', '4 Mayer Center');
insert into yrgo_records (person_number, student_name, student_address) values (5675, 'aliquam quis', '905 Badeau Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (9537, 'odio curabitur', '790 Stephen Alley');
insert into yrgo_records (person_number, student_name, student_address) values (9559, 'odio odio', '61 Sunbrook Pass');
insert into yrgo_records (person_number, student_name, student_address) values (5084, 'nunc rhoncus', '5627 Gale Circle');
insert into yrgo_records (person_number, student_name, student_address) values (6543, 'pede justo', '97346 Scofield Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1060, 'nunc rhoncus', '652 Golf Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (4896, 'mauris viverra', '319 Kropf Lane');
insert into yrgo_records (person_number, student_name, student_address) values (6990, 'tempor convallis', '3 Memorial Alley');
insert into yrgo_records (person_number, student_name, student_address) values (1802, 'augue aliquam', '99 Dovetail Center');
insert into yrgo_records (person_number, student_name, student_address) values (5518, 'sapien placerat', '0197 Mcguire Road');
insert into yrgo_records (person_number, student_name, student_address) values (5092, 'molestie lorem', '9 Jenna Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (7828, 'nullam porttitor', '278 Homewood Place');
insert into yrgo_records (person_number, student_name, student_address) values (5964, 'curae donec', '5 Anhalt Drive');
insert into yrgo_records (person_number, student_name, student_address) values (1676, 'luctus nec', '3 Bowman Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1510, 'donec diam', '87 Cascade Place');
insert into yrgo_records (person_number, student_name, student_address) values (3132, 'in quis', '61 Dunning Point');
insert into yrgo_records (person_number, student_name, student_address) values (6230, 'donec diam', '87054 Corscot Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1979, 'quisque ut', '3330 Arapahoe Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (8419, 'ante vivamus', '05572 Autumn Leaf Point');
insert into yrgo_records (person_number, student_name, student_address) values (2280, 'nulla ac', '94970 Eliot Road');
insert into yrgo_records (person_number, student_name, student_address) values (3437, 'praesent blandit', '7 Fulton Pass');
insert into yrgo_records (person_number, student_name, student_address) values (7679, 'ut rhoncus', '7 Elmside Court');
insert into yrgo_records (person_number, student_name, student_address) values (8124, 'luctus et', '7 Pepper Wood Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (8465, 'sagittis dui', '41323 Schmedeman Court');
insert into yrgo_records (person_number, student_name, student_address) values (8927, 'potenti in', '698 Rowland Place');
insert into yrgo_records (person_number, student_name, student_address) values (2596, 'orci luctus', '1041 Brown Road');
insert into yrgo_records (person_number, student_name, student_address) values (6935, 'quis justo', '4163 Hovde Court');
insert into yrgo_records (person_number, student_name, student_address) values (4595, 'pede libero', '49 Sommers Place');
insert into yrgo_records (person_number, student_name, student_address) values (9467, 'congue etiam', '91719 Thierer Place');
insert into yrgo_records (person_number, student_name, student_address) values (1095, 'bibendum felis', '444 Anniversary Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (6298, 'accumsan tellus', '50415 Transport Drive');
insert into yrgo_records (person_number, student_name, student_address) values (8442, 'ridiculus mus', '812 Lukken Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (8531, 'molestie lorem', '1 Forest Dale Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (2772, 'dapibus duis', '6890 Walton Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9903, 'elementum in', '3 Hudson Court');
insert into yrgo_records (person_number, student_name, student_address) values (5215, 'donec pharetra', '17 Rowland Place');
insert into yrgo_records (person_number, student_name, student_address) values (8486, 'morbi vestibulum', '09593 Commercial Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (7771, 'sem mauris', '6688 Luster Lane');
insert into yrgo_records (person_number, student_name, student_address) values (2909, 'ac neque', '0137 Ridge Oak Point');
insert into yrgo_records (person_number, student_name, student_address) values (1037, 'non mi', '88 Hauk Trail');
insert into yrgo_records (person_number, student_name, student_address) values (4284, 'nec dui', '79215 La Follette Center');
insert into yrgo_records (person_number, student_name, student_address) values (3608, 'vivamus in', '51811 Westridge Road');
insert into yrgo_records (person_number, student_name, student_address) values (7401, 'egestas metus', '8 Atwood Place');
insert into yrgo_records (person_number, student_name, student_address) values (2882, 'in hac', '6 Del Sol Pass');
insert into yrgo_records (person_number, student_name, student_address) values (8477, 'vestibulum proin', '2862 Buhler Junction');
insert into yrgo_records (person_number, student_name, student_address) values (3216, 'id nisl', '073 Esch Trail');
insert into yrgo_records (person_number, student_name, student_address) values (8461, 'parturient montes', '963 Magdeline Way');
insert into yrgo_records (person_number, student_name, student_address) values (7094, 'dictumst morbi', '95872 Rigney Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (8432, 'lectus in', '21743 Sommers Place');
insert into yrgo_records (person_number, student_name, student_address) values (1453, 'velit donec', '2848 Colorado Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (6520, 'nisl venenatis', '91995 Sachs Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2813, 'sed ante', '5 West Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (6770, 'nullam molestie', '3138 Ruskin Hill');
insert into yrgo_records (person_number, student_name, student_address) values (9177, 'eu nibh', '72431 Butternut Pass');
insert into yrgo_records (person_number, student_name, student_address) values (9560, 'maecenas leo', '16434 Pierstorff Pass');
insert into yrgo_records (person_number, student_name, student_address) values (9873, 'sed ante', '243 Jenna Pass');
insert into yrgo_records (person_number, student_name, student_address) values (3710, 'consequat varius', '2144 Hauk Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (8286, 'a nibh', '09754 Nelson Point');
insert into yrgo_records (person_number, student_name, student_address) values (6534, 'massa donec', '0356 Clove Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (4036, 'nisi volutpat', '3 Delladonna Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (7456, 'quam turpis', '46074 Mosinee Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7237, 'elit ac', '1 Bonner Point');
insert into yrgo_records (person_number, student_name, student_address) values (7120, 'suscipit ligula', '99864 American Ash Place');
insert into yrgo_records (person_number, student_name, student_address) values (1917, 'praesent lectus', '416 Granby Circle');
insert into yrgo_records (person_number, student_name, student_address) values (8063, 'dictumst maecenas', '885 Grasskamp Lane');
insert into yrgo_records (person_number, student_name, student_address) values (6468, 'diam nam', '5132 Monica Park');
insert into yrgo_records (person_number, student_name, student_address) values (4669, 'ante nulla', '7031 Warrior Trail');
insert into yrgo_records (person_number, student_name, student_address) values (3733, 'mauris vulputate', '437 Drewry Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (6351, 'iaculis diam', '20590 7th Street');
insert into yrgo_records (person_number, student_name, student_address) values (6737, 'nibh in', '67610 Mallory Lane');
insert into yrgo_records (person_number, student_name, student_address) values (2334, 'interdum mauris', '4 Hazelcrest Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (2476, 'iaculis justo', '72039 Anzinger Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (8334, 'at dolor', '3 Shoshone Hill');
insert into yrgo_records (person_number, student_name, student_address) values (1725, 'integer a', '41 Ridgeview Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (7753, 'proin at', '203 Jenna Drive');
insert into yrgo_records (person_number, student_name, student_address) values (5707, 'pellentesque volutpat', '96 Karstens Road');
insert into yrgo_records (person_number, student_name, student_address) values (9649, 'suspendisse potenti', '793 Roth Court');
insert into yrgo_records (person_number, student_name, student_address) values (1904, 'curabitur gravida', '0 David Trail');
insert into yrgo_records (person_number, student_name, student_address) values (8192, 'cursus vestibulum', '5 Michigan Pass');
insert into yrgo_records (person_number, student_name, student_address) values (6541, 'parturient montes', '34 Russell Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (1523, 'sapien non', '2360 Pankratz Pass');
insert into yrgo_records (person_number, student_name, student_address) values (8677, 'feugiat non', '3 Lotheville Alley');
insert into yrgo_records (person_number, student_name, student_address) values (6972, 'lacus morbi', '5 Fisk Hill');
insert into yrgo_records (person_number, student_name, student_address) values (3227, 'eget vulputate', '43861 Lindbergh Street');
insert into yrgo_records (person_number, student_name, student_address) values (4376, 'eu massa', '5394 Northland Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (1093, 'vestibulum rutrum', '0 Summerview Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (1826, 'adipiscing molestie', '8 Bartelt Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (7119, 'pharetra magna', '4 Amoth Alley');
insert into yrgo_records (person_number, student_name, student_address) values (6657, 'nisl nunc', '54227 Sommers Pass');
insert into yrgo_records (person_number, student_name, student_address) values (8460, 'luctus et', '1112 Walton Center');
insert into yrgo_records (person_number, student_name, student_address) values (3684, 'dui maecenas', '1380 Sullivan Drive');
insert into yrgo_records (person_number, student_name, student_address) values (3828, 'morbi non', '23 Old Shore Lane');
insert into yrgo_records (person_number, student_name, student_address) values (9433, 'eget nunc', '5275 Roth Center');
insert into yrgo_records (person_number, student_name, student_address) values (6068, 'ullamcorper purus', '15693 Basil Circle');
insert into yrgo_records (person_number, student_name, student_address) values (6551, 'et magnis', '6139 Mallard Lane');
insert into yrgo_records (person_number, student_name, student_address) values (8456, 'et ultrices', '4 Blackbird Center');
insert into yrgo_records (person_number, student_name, student_address) values (4103, 'in tempus', '5 Anniversary Park');
insert into yrgo_records (person_number, student_name, student_address) values (5894, 'in purus', '83 Blue Bill Park Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (3859, 'morbi quis', '45 Pierstorff Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4055, 'nulla facilisi', '0 Spaight Drive');
insert into yrgo_records (person_number, student_name, student_address) values (7312, 'turpis elementum', '2648 Butternut Circle');
insert into yrgo_records (person_number, student_name, student_address) values (7848, 'elementum in', '591 Luster Trail');
insert into yrgo_records (person_number, student_name, student_address) values (5342, 'donec semper', '941 Haas Circle');
insert into yrgo_records (person_number, student_name, student_address) values (1333, 'tempus semper', '92 Anniversary Court');
insert into yrgo_records (person_number, student_name, student_address) values (5376, 'tincidunt eget', '57 Vahlen Center');
insert into yrgo_records (person_number, student_name, student_address) values (8866, 'quisque porta', '6 Huxley Park');
insert into yrgo_records (person_number, student_name, student_address) values (4908, 'sapien ut', '32 Melvin Place');
insert into yrgo_records (person_number, student_name, student_address) values (8068, 'orci mauris', '49974 Jenifer Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (2339, 'lacinia nisi', '04 East Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (6623, 'ut blandit', '3 Superior Place');
insert into yrgo_records (person_number, student_name, student_address) values (2989, 'maecenas leo', '40 Spohn Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (8384, 'erat vestibulum', '6665 Stoughton Center');
insert into yrgo_records (person_number, student_name, student_address) values (6025, 'nec molestie', '44 Sachtjen Hill');
insert into yrgo_records (person_number, student_name, student_address) values (4410, 'duis consequat', '42801 Prairieview Alley');
insert into yrgo_records (person_number, student_name, student_address) values (3860, 'magnis dis', '451 5th Center');
insert into yrgo_records (person_number, student_name, student_address) values (6685, 'ipsum primis', '27 Sachtjen Street');
insert into yrgo_records (person_number, student_name, student_address) values (1093, 'in tempus', '61 Continental Road');
insert into yrgo_records (person_number, student_name, student_address) values (3914, 'nulla sed', '04211 Spenser Pass');
insert into yrgo_records (person_number, student_name, student_address) values (7475, 'venenatis turpis', '5 Anniversary Pass');
insert into yrgo_records (person_number, student_name, student_address) values (3283, 'at ipsum', '4551 Tennyson Road');
insert into yrgo_records (person_number, student_name, student_address) values (6144, 'in faucibus', '44 Meadow Valley Hill');
insert into yrgo_records (person_number, student_name, student_address) values (3108, 'nibh ligula', '5816 Jackson Way');
insert into yrgo_records (person_number, student_name, student_address) values (1085, 'purus aliquet', '61757 Melvin Drive');
insert into yrgo_records (person_number, student_name, student_address) values (4045, 'vestibulum quam', '359 Lakewood Street');
insert into yrgo_records (person_number, student_name, student_address) values (7156, 'tempor convallis', '270 Debs Park');
insert into yrgo_records (person_number, student_name, student_address) values (3873, 'dapibus nulla', '28 Harper Place');
insert into yrgo_records (person_number, student_name, student_address) values (8337, 'eu sapien', '0666 Hoepker Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1803, 'sed tincidunt', '00 Moland Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (1738, 'lacinia nisi', '6305 Shopko Point');
insert into yrgo_records (person_number, student_name, student_address) values (5712, 'quam suspendisse', '10 Eagan Place');
insert into yrgo_records (person_number, student_name, student_address) values (1681, 'felis sed', '836 Melvin Drive');
insert into yrgo_records (person_number, student_name, student_address) values (5324, 'donec ut', '80705 Sommers Lane');
insert into yrgo_records (person_number, student_name, student_address) values (8573, 'platea dictumst', '962 Golf View Way');
insert into yrgo_records (person_number, student_name, student_address) values (1927, 'cras non', '66 Crest Line Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4743, 'sapien dignissim', '8 Kim Drive');
insert into yrgo_records (person_number, student_name, student_address) values (8862, 'non mauris', '264 Barnett Trail');
insert into yrgo_records (person_number, student_name, student_address) values (9532, 'rhoncus mauris', '86 Melody Hill');
insert into yrgo_records (person_number, student_name, student_address) values (5700, 'nisl venenatis', '7 Forster Circle');
insert into yrgo_records (person_number, student_name, student_address) values (6250, 'lorem ipsum', '9 Carpenter Street');
insert into yrgo_records (person_number, student_name, student_address) values (4422, 'nisl duis', '338 8th Hill');
insert into yrgo_records (person_number, student_name, student_address) values (3142, 'purus sit', '743 Bultman Center');
insert into yrgo_records (person_number, student_name, student_address) values (4157, 'mattis odio', '902 Rieder Court');
insert into yrgo_records (person_number, student_name, student_address) values (2559, 'habitasse platea', '8441 Sutherland Pass');
insert into yrgo_records (person_number, student_name, student_address) values (2628, 'nonummy integer', '0336 Hermina Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (1094, 'nunc viverra', '69 Main Place');
insert into yrgo_records (person_number, student_name, student_address) values (4759, 'augue a', '8022 Crest Line Circle');
insert into yrgo_records (person_number, student_name, student_address) values (7261, 'suscipit ligula', '5597 Redwing Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (8214, 'ridiculus mus', '9230 Morrow Drive');
insert into yrgo_records (person_number, student_name, student_address) values (7021, 'duis bibendum', '5 Grim Circle');
insert into yrgo_records (person_number, student_name, student_address) values (9957, 'ut mauris', '42154 Derek Court');
insert into yrgo_records (person_number, student_name, student_address) values (7673, 'nulla eget', '3 Stoughton Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (3073, 'sed nisl', '95360 Bultman Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (9540, 'pede venenatis', '15487 Debs Drive');
insert into yrgo_records (person_number, student_name, student_address) values (7660, 'sodales scelerisque', '999 Sutteridge Street');
insert into yrgo_records (person_number, student_name, student_address) values (9404, 'suspendisse potenti', '17 Schurz Junction');
insert into yrgo_records (person_number, student_name, student_address) values (7990, 'tempus vel', '65088 Kingsford Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9044, 'donec semper', '6554 Commercial Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (5087, 'suspendisse potenti', '223 Cody Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1763, 'duis faucibus', '5421 Cardinal Point');
insert into yrgo_records (person_number, student_name, student_address) values (2096, 'quam fringilla', '031 Sachtjen Trail');
insert into yrgo_records (person_number, student_name, student_address) values (2850, 'bibendum morbi', '04 Roth Circle');
insert into yrgo_records (person_number, student_name, student_address) values (2298, 'justo sollicitudin', '472 Eliot Pass');
insert into yrgo_records (person_number, student_name, student_address) values (9597, 'pede posuere', '01471 Tennyson Street');
insert into yrgo_records (person_number, student_name, student_address) values (4411, 'sit amet', '236 Dottie Center');
insert into yrgo_records (person_number, student_name, student_address) values (5126, 'quis turpis', '94387 Di Loreto Hill');
insert into yrgo_records (person_number, student_name, student_address) values (5073, 'potenti cras', '030 Manitowish Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (8822, 'rhoncus sed', '32834 Hoffman Way');
insert into yrgo_records (person_number, student_name, student_address) values (2147, 'consectetuer eget', '78995 Eagle Crest Hill');
insert into yrgo_records (person_number, student_name, student_address) values (4712, 'posuere metus', '1 Quincy Alley');
insert into yrgo_records (person_number, student_name, student_address) values (1894, 'nulla dapibus', '8240 Knutson Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (1524, 'sem mauris', '21808 Burning Wood Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (6144, 'in faucibus', '4901 Vidon Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (1203, 'at turpis', '109 Northwestern Road');
insert into yrgo_records (person_number, student_name, student_address) values (8529, 'pede justo', '23644 Oakridge Place');
insert into yrgo_records (person_number, student_name, student_address) values (5792, 'ante vivamus', '52262 Helena Drive');
insert into yrgo_records (person_number, student_name, student_address) values (8316, 'in ante', '0 David Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (4885, 'donec ut', '18 Mccormick Junction');
insert into yrgo_records (person_number, student_name, student_address) values (4157, 'dolor sit', '01 Cottonwood Park');
insert into yrgo_records (person_number, student_name, student_address) values (6774, 'quam turpis', '52 Bonner Junction');
insert into yrgo_records (person_number, student_name, student_address) values (9007, 'ut erat', '96746 Towne Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (4236, 'diam id', '53 Killdeer Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (2189, 'adipiscing elit', '67 Holy Cross Center');
insert into yrgo_records (person_number, student_name, student_address) values (5547, 'eu massa', '67 Messerschmidt Park');
insert into yrgo_records (person_number, student_name, student_address) values (4528, 'vehicula condimentum', '71 Northridge Place');
insert into yrgo_records (person_number, student_name, student_address) values (2879, 'nulla justo', '8788 Coolidge Drive');
insert into yrgo_records (person_number, student_name, student_address) values (8355, 'turpis donec', '3 Lien Place');
insert into yrgo_records (person_number, student_name, student_address) values (3890, 'in sagittis', '20078 Norway Maple Drive');
insert into yrgo_records (person_number, student_name, student_address) values (1763, 'pulvinar lobortis', '37967 Dottie Road');
insert into yrgo_records (person_number, student_name, student_address) values (3872, 'ipsum primis', '66221 Marquette Junction');
insert into yrgo_records (person_number, student_name, student_address) values (1411, 'mus etiam', '311 Melody Point');
insert into yrgo_records (person_number, student_name, student_address) values (6071, 'sagittis nam', '622 Lien Road');
insert into yrgo_records (person_number, student_name, student_address) values (1682, 'nec condimentum', '98331 Fremont Trail');
insert into yrgo_records (person_number, student_name, student_address) values (1712, 'nulla tempus', '0270 Twin Pines Way');
insert into yrgo_records (person_number, student_name, student_address) values (7464, 'hac habitasse', '2055 Hazelcrest Court');
insert into yrgo_records (person_number, student_name, student_address) values (3859, 'in blandit', '3 Sunfield Drive');
insert into yrgo_records (person_number, student_name, student_address) values (7765, 'nibh quisque', '0370 Fremont Circle');
insert into yrgo_records (person_number, student_name, student_address) values (5320, 'metus arcu', '2 Cascade Circle');
insert into yrgo_records (person_number, student_name, student_address) values (3273, 'hac habitasse', '23 Algoma Circle');
insert into yrgo_records (person_number, student_name, student_address) values (9282, 'diam neque', '49731 Comanche Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (5375, 'vestibulum rutrum', '91478 Kim Alley');
insert into yrgo_records (person_number, student_name, student_address) values (1124, 'elit proin', '580 Union Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (7967, 'id lobortis', '4052 Troy Pass');
insert into yrgo_records (person_number, student_name, student_address) values (8029, 'nullam sit', '173 Fairfield Hill');
insert into yrgo_records (person_number, student_name, student_address) values (3878, 'sodales scelerisque', '826 Wayridge Junction');
insert into yrgo_records (person_number, student_name, student_address) values (3051, 'duis at', '39 Thackeray Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (8265, 'ut suscipit', '60 Eggendart Center');
insert into yrgo_records (person_number, student_name, student_address) values (8189, 'tincidunt in', '61 Fair Oaks Point');
insert into yrgo_records (person_number, student_name, student_address) values (4018, 'sed vestibulum', '79821 Canary Park');
insert into yrgo_records (person_number, student_name, student_address) values (8477, 'eros vestibulum', '8770 Hintze Center');
insert into yrgo_records (person_number, student_name, student_address) values (6594, 'consectetuer adipiscing', '763 Bashford Point');
insert into yrgo_records (person_number, student_name, student_address) values (1382, 'metus aenean', '2 Dapin Trail');
insert into yrgo_records (person_number, student_name, student_address) values (2214, 'ac neque', '8137 Jenifer Trail');
insert into yrgo_records (person_number, student_name, student_address) values (2525, 'lorem integer', '316 Coleman Crossing');
insert into yrgo_records (person_number, student_name, student_address) values (8001, 'et ultrices', '7432 Starling Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (9252, 'blandit mi', '51766 Hayes Drive');
insert into yrgo_records (person_number, student_name, student_address) values (6336, 'quam a', '64745 Hovde Drive');
insert into yrgo_records (person_number, student_name, student_address) values (6906, 'duis bibendum', '1501 Village Parkway');
insert into yrgo_records (person_number, student_name, student_address) values (3757, 'lectus in', '79 Sage Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (3464, 'aliquam non', '0 West Plaza');
insert into yrgo_records (person_number, student_name, student_address) values (4745, 'massa volutpat', '97 Monument Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (7029, 'nulla suspendisse', '6 Rigney Center');
insert into yrgo_records (person_number, student_name, student_address) values (1930, 'tincidunt nulla', '943 Killdeer Terrace');
insert into yrgo_records (person_number, student_name, student_address) values (4883, 'lectus pellentesque', '141 Old Gate Circle');
insert into yrgo_records (person_number, student_name, student_address) values (6508, 'orci vehicula', '301 Harbort Avenue');
insert into yrgo_records (person_number, student_name, student_address) values (5545, 'sit amet', '42 Novick Trail');
